// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskPrerequisiteRef } from './TaskPrerequisiteRef';
import {
    TaskPrerequisiteRefFromJSON,
    TaskPrerequisiteRefFromJSONTyped,
    TaskPrerequisiteRefToJSON,
    TaskPrerequisiteRefToJSONTyped,
} from './TaskPrerequisiteRef';

/**
 * Reviewed generated Backlog task draft.
 * @export
 * @interface BacklogTaskDraftCreate
 */
export interface BacklogTaskDraftCreate {
    /**
     * 
     * @type {string}
     * @memberof BacklogTaskDraftCreate
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof BacklogTaskDraftCreate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof BacklogTaskDraftCreate
     */
    priority?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BacklogTaskDraftCreate
     */
    storyPoints?: number | null;
    /**
     * 
     * @type {string}
     * @memberof BacklogTaskDraftCreate
     */
    assigneeId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BacklogTaskDraftCreate
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BacklogTaskDraftCreate
     */
    acceptanceCriteria?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BacklogTaskDraftCreate
     */
    tag?: string | null;
    /**
     * 
     * @type {Array<TaskPrerequisiteRef>}
     * @memberof BacklogTaskDraftCreate
     */
    prerequisites?: Array<TaskPrerequisiteRef>;
}

/**
 * Check if a given object implements the BacklogTaskDraftCreate interface.
 */
export function instanceOfBacklogTaskDraftCreate(value: object): value is BacklogTaskDraftCreate {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function BacklogTaskDraftCreateFromJSON(json: any): BacklogTaskDraftCreate {
    return BacklogTaskDraftCreateFromJSONTyped(json, false);
}

export function BacklogTaskDraftCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): BacklogTaskDraftCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'title': json['title'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'storyPoints': json['story_points'] == null ? undefined : json['story_points'],
        'assigneeId': json['assignee_id'] == null ? undefined : json['assignee_id'],
        'description': json['description'] == null ? undefined : json['description'],
        'acceptanceCriteria': json['acceptance_criteria'] == null ? undefined : json['acceptance_criteria'],
        'tag': json['tag'] == null ? undefined : json['tag'],
        'prerequisites': json['prerequisites'] == null ? undefined : ((json['prerequisites'] as Array<any>).map(TaskPrerequisiteRefFromJSON)),
    };
}

export function BacklogTaskDraftCreateToJSON(json: any): BacklogTaskDraftCreate {
    return BacklogTaskDraftCreateToJSONTyped(json, false);
}

export function BacklogTaskDraftCreateToJSONTyped(value?: BacklogTaskDraftCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'title': value['title'],
        'priority': value['priority'],
        'story_points': value['storyPoints'],
        'assignee_id': value['assigneeId'],
        'description': value['description'],
        'acceptance_criteria': value['acceptanceCriteria'],
        'tag': value['tag'],
        'prerequisites': value['prerequisites'] == null ? undefined : ((value['prerequisites'] as Array<any>).map(TaskPrerequisiteRefToJSON)),
    };
}

