// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BacklogTaskDraftCreate } from './BacklogTaskDraftCreate';
import {
    BacklogTaskDraftCreateFromJSON,
    BacklogTaskDraftCreateFromJSONTyped,
    BacklogTaskDraftCreateToJSON,
    BacklogTaskDraftCreateToJSONTyped,
} from './BacklogTaskDraftCreate';

/**
 * Atomic reviewed draft save request.
 * @export
 * @interface BacklogTaskBulkCreate
 */
export interface BacklogTaskBulkCreate {
    /**
     * 
     * @type {Array<BacklogTaskDraftCreate>}
     * @memberof BacklogTaskBulkCreate
     */
    tasks: Array<BacklogTaskDraftCreate>;
}

/**
 * Check if a given object implements the BacklogTaskBulkCreate interface.
 */
export function instanceOfBacklogTaskBulkCreate(value: object): value is BacklogTaskBulkCreate {
    if (!('tasks' in value) || value['tasks'] === undefined) return false;
    return true;
}

export function BacklogTaskBulkCreateFromJSON(json: any): BacklogTaskBulkCreate {
    return BacklogTaskBulkCreateFromJSONTyped(json, false);
}

export function BacklogTaskBulkCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): BacklogTaskBulkCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'tasks': ((json['tasks'] as Array<any>).map(BacklogTaskDraftCreateFromJSON)),
    };
}

export function BacklogTaskBulkCreateToJSON(json: any): BacklogTaskBulkCreate {
    return BacklogTaskBulkCreateToJSONTyped(json, false);
}

export function BacklogTaskBulkCreateToJSONTyped(value?: BacklogTaskBulkCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tasks': ((value['tasks'] as Array<any>).map(BacklogTaskDraftCreateToJSON)),
    };
}

