// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request payload for adding an existing task to the active sprint.
 * @export
 * @interface ProjectSprintTaskAdd
 */
export interface ProjectSprintTaskAdd {
    /**
     * 
     * @type {string}
     * @memberof ProjectSprintTaskAdd
     */
    taskId: string;
}

/**
 * Check if a given object implements the ProjectSprintTaskAdd interface.
 */
export function instanceOfProjectSprintTaskAdd(value: object): value is ProjectSprintTaskAdd {
    if (!('taskId' in value) || value['taskId'] === undefined) return false;
    return true;
}

export function ProjectSprintTaskAddFromJSON(json: any): ProjectSprintTaskAdd {
    return ProjectSprintTaskAddFromJSONTyped(json, false);
}

export function ProjectSprintTaskAddFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectSprintTaskAdd {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['task_id'],
    };
}

export function ProjectSprintTaskAddToJSON(json: any): ProjectSprintTaskAdd {
    return ProjectSprintTaskAddToJSONTyped(json, false);
}

export function ProjectSprintTaskAddToJSONTyped(value?: ProjectSprintTaskAdd | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'task_id': value['taskId'],
    };
}

