// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request payload for creating a project workflow column.
 * @export
 * @interface ProjectColumnCreate
 */
export interface ProjectColumnCreate {
    /**
     * 
     * @type {string}
     * @memberof ProjectColumnCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectColumnCreate
     */
    description?: string | null;
}

/**
 * Check if a given object implements the ProjectColumnCreate interface.
 */
export function instanceOfProjectColumnCreate(value: object): value is ProjectColumnCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ProjectColumnCreateFromJSON(json: any): ProjectColumnCreate {
    return ProjectColumnCreateFromJSONTyped(json, false);
}

export function ProjectColumnCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectColumnCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ProjectColumnCreateToJSON(json: any): ProjectColumnCreate {
    return ProjectColumnCreateToJSONTyped(json, false);
}

export function ProjectColumnCreateToJSONTyped(value?: ProjectColumnCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

