// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request payload for rewriting project Backlog order.
 * @export
 * @interface ProjectBacklogReorder
 */
export interface ProjectBacklogReorder {
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectBacklogReorder
     */
    taskIds: Array<string>;
}

/**
 * Check if a given object implements the ProjectBacklogReorder interface.
 */
export function instanceOfProjectBacklogReorder(value: object): value is ProjectBacklogReorder {
    if (!('taskIds' in value) || value['taskIds'] === undefined) return false;
    return true;
}

export function ProjectBacklogReorderFromJSON(json: any): ProjectBacklogReorder {
    return ProjectBacklogReorderFromJSONTyped(json, false);
}

export function ProjectBacklogReorderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectBacklogReorder {
    if (json == null) {
        return json;
    }
    return {
        
        'taskIds': json['task_ids'],
    };
}

export function ProjectBacklogReorderToJSON(json: any): ProjectBacklogReorder {
    return ProjectBacklogReorderToJSONTyped(json, false);
}

export function ProjectBacklogReorderToJSONTyped(value?: ProjectBacklogReorder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'task_ids': value['taskIds'],
    };
}

