// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request payload for reordering all project workflow columns.
 * @export
 * @interface ProjectColumnReorder
 */
export interface ProjectColumnReorder {
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectColumnReorder
     */
    columnIds: Array<string>;
}

/**
 * Check if a given object implements the ProjectColumnReorder interface.
 */
export function instanceOfProjectColumnReorder(value: object): value is ProjectColumnReorder {
    if (!('columnIds' in value) || value['columnIds'] === undefined) return false;
    return true;
}

export function ProjectColumnReorderFromJSON(json: any): ProjectColumnReorder {
    return ProjectColumnReorderFromJSONTyped(json, false);
}

export function ProjectColumnReorderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectColumnReorder {
    if (json == null) {
        return json;
    }
    return {
        
        'columnIds': json['column_ids'],
    };
}

export function ProjectColumnReorderToJSON(json: any): ProjectColumnReorder {
    return ProjectColumnReorderToJSONTyped(json, false);
}

export function ProjectColumnReorderToJSONTyped(value?: ProjectColumnReorder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'column_ids': value['columnIds'],
    };
}

