// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Defines a project sprint response payload.
 * @export
 * @interface ProjectSprintRead
 */
export interface ProjectSprintRead {
    /**
     * 
     * @type {string}
     * @memberof ProjectSprintRead
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectSprintRead
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectSprintRead
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectSprintRead
     */
    lifecycleState: string;
    /**
     * 
     * @type {Date}
     * @memberof ProjectSprintRead
     */
    plannedStartDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProjectSprintRead
     */
    plannedEndDate: Date;
    /**
     * 
     * @type {string}
     * @memberof ProjectSprintRead
     */
    goal: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ProjectSprintRead
     */
    closedAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ProjectSprintRead
     */
    createdAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ProjectSprintRead
     */
    updatedAt: Date | null;
}

/**
 * Check if a given object implements the ProjectSprintRead interface.
 */
export function instanceOfProjectSprintRead(value: object): value is ProjectSprintRead {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('lifecycleState' in value) || value['lifecycleState'] === undefined) return false;
    if (!('plannedStartDate' in value) || value['plannedStartDate'] === undefined) return false;
    if (!('plannedEndDate' in value) || value['plannedEndDate'] === undefined) return false;
    if (!('goal' in value) || value['goal'] === undefined) return false;
    if (!('closedAt' in value) || value['closedAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ProjectSprintReadFromJSON(json: any): ProjectSprintRead {
    return ProjectSprintReadFromJSONTyped(json, false);
}

export function ProjectSprintReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectSprintRead {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'projectId': json['project_id'],
        'name': json['name'],
        'lifecycleState': json['lifecycle_state'],
        'plannedStartDate': (new Date(json['planned_start_date'])),
        'plannedEndDate': (new Date(json['planned_end_date'])),
        'goal': json['goal'],
        'closedAt': (json['closed_at'] == null ? null : new Date(json['closed_at'])),
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'updatedAt': (json['updated_at'] == null ? null : new Date(json['updated_at'])),
    };
}

export function ProjectSprintReadToJSON(json: any): ProjectSprintRead {
    return ProjectSprintReadToJSONTyped(json, false);
}

export function ProjectSprintReadToJSONTyped(value?: ProjectSprintRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'project_id': value['projectId'],
        'name': value['name'],
        'lifecycle_state': value['lifecycleState'],
        'planned_start_date': value['plannedStartDate'].toISOString().substring(0,10),
        'planned_end_date': value['plannedEndDate'].toISOString().substring(0,10),
        'goal': value['goal'],
        'closed_at': value['closedAt'] == null ? value['closedAt'] : value['closedAt'].toISOString(),
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

