// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Defines the project response payload.
 * 
 * Attributes:
 *     id: Project identifier.
 *     name: Project display name.
 *     code: Three-character project code.
 *     priority: Project priority label.
 *     description: Optional project description.
 *     status: Optional project status label.
 *     owner_ids: User IDs assigned as project owners.
 *     member_ids: User IDs assigned as project members.
 *     created_at: Optional timestamp when the project was created.
 *     updated_at: Optional timestamp when the project was last updated.
 * @export
 * @interface ProjectRead
 */
export interface ProjectRead {
    /**
     * 
     * @type {string}
     * @memberof ProjectRead
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectRead
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectRead
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectRead
     */
    priority: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectRead
     */
    description: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectRead
     */
    status: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectRead
     */
    ownerIds: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectRead
     */
    memberIds: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof ProjectRead
     */
    createdAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ProjectRead
     */
    updatedAt: Date | null;
}

/**
 * Check if a given object implements the ProjectRead interface.
 */
export function instanceOfProjectRead(value: object): value is ProjectRead {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('ownerIds' in value) || value['ownerIds'] === undefined) return false;
    if (!('memberIds' in value) || value['memberIds'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ProjectReadFromJSON(json: any): ProjectRead {
    return ProjectReadFromJSONTyped(json, false);
}

export function ProjectReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectRead {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'code': json['code'],
        'priority': json['priority'],
        'description': json['description'],
        'status': json['status'],
        'ownerIds': json['owner_ids'],
        'memberIds': json['member_ids'],
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'updatedAt': (json['updated_at'] == null ? null : new Date(json['updated_at'])),
    };
}

export function ProjectReadToJSON(json: any): ProjectRead {
    return ProjectReadToJSONTyped(json, false);
}

export function ProjectReadToJSONTyped(value?: ProjectRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'code': value['code'],
        'priority': value['priority'],
        'description': value['description'],
        'status': value['status'],
        'owner_ids': value['ownerIds'],
        'member_ids': value['memberIds'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

