// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectSprintRead } from './ProjectSprintRead';
import {
    ProjectSprintReadFromJSON,
    ProjectSprintReadFromJSONTyped,
    ProjectSprintReadToJSON,
    ProjectSprintReadToJSONTyped,
} from './ProjectSprintRead';
import type { TaskRead } from './TaskRead';
import {
    TaskReadFromJSON,
    TaskReadFromJSONTyped,
    TaskReadToJSON,
    TaskReadToJSONTyped,
} from './TaskRead';
import type { ProjectSprintTaskSnapshotRead } from './ProjectSprintTaskSnapshotRead';
import {
    ProjectSprintTaskSnapshotReadFromJSON,
    ProjectSprintTaskSnapshotReadFromJSONTyped,
    ProjectSprintTaskSnapshotReadToJSON,
    ProjectSprintTaskSnapshotReadToJSONTyped,
} from './ProjectSprintTaskSnapshotRead';

/**
 * Response payload after a sprint has been closed.
 * @export
 * @interface ProjectSprintCloseRead
 */
export interface ProjectSprintCloseRead {
    /**
     * 
     * @type {ProjectSprintRead}
     * @memberof ProjectSprintCloseRead
     */
    sprint: ProjectSprintRead;
    /**
     * 
     * @type {number}
     * @memberof ProjectSprintCloseRead
     */
    finishedCount: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectSprintCloseRead
     */
    unfinishedCount: number;
    /**
     * 
     * @type {Array<TaskRead>}
     * @memberof ProjectSprintCloseRead
     */
    unfinishedTasks: Array<TaskRead>;
    /**
     * 
     * @type {string}
     * @memberof ProjectSprintCloseRead
     */
    carryoverStatement: string;
    /**
     * 
     * @type {Array<ProjectSprintTaskSnapshotRead>}
     * @memberof ProjectSprintCloseRead
     */
    snapshots: Array<ProjectSprintTaskSnapshotRead>;
}

/**
 * Check if a given object implements the ProjectSprintCloseRead interface.
 */
export function instanceOfProjectSprintCloseRead(value: object): value is ProjectSprintCloseRead {
    if (!('sprint' in value) || value['sprint'] === undefined) return false;
    if (!('finishedCount' in value) || value['finishedCount'] === undefined) return false;
    if (!('unfinishedCount' in value) || value['unfinishedCount'] === undefined) return false;
    if (!('unfinishedTasks' in value) || value['unfinishedTasks'] === undefined) return false;
    if (!('carryoverStatement' in value) || value['carryoverStatement'] === undefined) return false;
    if (!('snapshots' in value) || value['snapshots'] === undefined) return false;
    return true;
}

export function ProjectSprintCloseReadFromJSON(json: any): ProjectSprintCloseRead {
    return ProjectSprintCloseReadFromJSONTyped(json, false);
}

export function ProjectSprintCloseReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectSprintCloseRead {
    if (json == null) {
        return json;
    }
    return {
        
        'sprint': ProjectSprintReadFromJSON(json['sprint']),
        'finishedCount': json['finished_count'],
        'unfinishedCount': json['unfinished_count'],
        'unfinishedTasks': ((json['unfinished_tasks'] as Array<any>).map(TaskReadFromJSON)),
        'carryoverStatement': json['carryover_statement'],
        'snapshots': ((json['snapshots'] as Array<any>).map(ProjectSprintTaskSnapshotReadFromJSON)),
    };
}

export function ProjectSprintCloseReadToJSON(json: any): ProjectSprintCloseRead {
    return ProjectSprintCloseReadToJSONTyped(json, false);
}

export function ProjectSprintCloseReadToJSONTyped(value?: ProjectSprintCloseRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sprint': ProjectSprintReadToJSON(value['sprint']),
        'finished_count': value['finishedCount'],
        'unfinished_count': value['unfinishedCount'],
        'unfinished_tasks': ((value['unfinishedTasks'] as Array<any>).map(TaskReadToJSON)),
        'carryover_statement': value['carryoverStatement'],
        'snapshots': ((value['snapshots'] as Array<any>).map(ProjectSprintTaskSnapshotReadToJSON)),
    };
}

