// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Empty-state metadata for a dashboard chart card.
 * @export
 * @interface ProjectDashboardCardEmptyStateRead
 */
export interface ProjectDashboardCardEmptyStateRead {
    /**
     * 
     * @type {string}
     * @memberof ProjectDashboardCardEmptyStateRead
     */
    reason: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDashboardCardEmptyStateRead
     */
    message: string;
}

/**
 * Check if a given object implements the ProjectDashboardCardEmptyStateRead interface.
 */
export function instanceOfProjectDashboardCardEmptyStateRead(value: object): value is ProjectDashboardCardEmptyStateRead {
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ProjectDashboardCardEmptyStateReadFromJSON(json: any): ProjectDashboardCardEmptyStateRead {
    return ProjectDashboardCardEmptyStateReadFromJSONTyped(json, false);
}

export function ProjectDashboardCardEmptyStateReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDashboardCardEmptyStateRead {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'],
        'message': json['message'],
    };
}

export function ProjectDashboardCardEmptyStateReadToJSON(json: any): ProjectDashboardCardEmptyStateRead {
    return ProjectDashboardCardEmptyStateReadToJSONTyped(json, false);
}

export function ProjectDashboardCardEmptyStateReadToJSONTyped(value?: ProjectDashboardCardEmptyStateRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
        'message': value['message'],
    };
}

