// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Defines a project workflow column response payload.
 * @export
 * @interface ProjectColumnRead
 */
export interface ProjectColumnRead {
    /**
     * 
     * @type {string}
     * @memberof ProjectColumnRead
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectColumnRead
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectColumnRead
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ProjectColumnRead
     */
    position: number;
    /**
     * 
     * @type {Date}
     * @memberof ProjectColumnRead
     */
    createdAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ProjectColumnRead
     */
    updatedAt: Date | null;
}

/**
 * Check if a given object implements the ProjectColumnRead interface.
 */
export function instanceOfProjectColumnRead(value: object): value is ProjectColumnRead {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('position' in value) || value['position'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ProjectColumnReadFromJSON(json: any): ProjectColumnRead {
    return ProjectColumnReadFromJSONTyped(json, false);
}

export function ProjectColumnReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectColumnRead {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'projectId': json['project_id'],
        'name': json['name'],
        'position': json['position'],
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'updatedAt': (json['updated_at'] == null ? null : new Date(json['updated_at'])),
    };
}

export function ProjectColumnReadToJSON(json: any): ProjectColumnRead {
    return ProjectColumnReadToJSONTyped(json, false);
}

export function ProjectColumnReadToJSONTyped(value?: ProjectColumnRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'project_id': value['projectId'],
        'name': value['name'],
        'position': value['position'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

