// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request payload for creating a project sprint.
 * @export
 * @interface ProjectSprintCreate
 */
export interface ProjectSprintCreate {
    /**
     * 
     * @type {Date}
     * @memberof ProjectSprintCreate
     */
    plannedStartDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProjectSprintCreate
     */
    plannedEndDate: Date;
    /**
     * 
     * @type {string}
     * @memberof ProjectSprintCreate
     */
    goal?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectSprintCreate
     */
    taskIds?: Array<string>;
}

/**
 * Check if a given object implements the ProjectSprintCreate interface.
 */
export function instanceOfProjectSprintCreate(value: object): value is ProjectSprintCreate {
    if (!('plannedStartDate' in value) || value['plannedStartDate'] === undefined) return false;
    if (!('plannedEndDate' in value) || value['plannedEndDate'] === undefined) return false;
    return true;
}

export function ProjectSprintCreateFromJSON(json: any): ProjectSprintCreate {
    return ProjectSprintCreateFromJSONTyped(json, false);
}

export function ProjectSprintCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectSprintCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'plannedStartDate': (new Date(json['planned_start_date'])),
        'plannedEndDate': (new Date(json['planned_end_date'])),
        'goal': json['goal'] == null ? undefined : json['goal'],
        'taskIds': json['task_ids'] == null ? undefined : json['task_ids'],
    };
}

export function ProjectSprintCreateToJSON(json: any): ProjectSprintCreate {
    return ProjectSprintCreateToJSONTyped(json, false);
}

export function ProjectSprintCreateToJSONTyped(value?: ProjectSprintCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'planned_start_date': value['plannedStartDate'].toISOString().substring(0,10),
        'planned_end_date': value['plannedEndDate'].toISOString().substring(0,10),
        'goal': value['goal'],
        'task_ids': value['taskIds'],
    };
}

