// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Historical task snapshot captured when a sprint closes.
 * @export
 * @interface ProjectSprintTaskSnapshotRead
 */
export interface ProjectSprintTaskSnapshotRead {
    /**
     * 
     * @type {string}
     * @memberof ProjectSprintTaskSnapshotRead
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectSprintTaskSnapshotRead
     */
    sprintId: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectSprintTaskSnapshotRead
     */
    taskId: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectSprintTaskSnapshotRead
     */
    columnId: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectSprintTaskSnapshotRead
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectSprintTaskSnapshotRead
     */
    outcome: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectSprintTaskSnapshotRead
     */
    priority: string | null;
    /**
     * 
     * @type {number}
     * @memberof ProjectSprintTaskSnapshotRead
     */
    storyPoints: number | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectSprintTaskSnapshotRead
     */
    rank: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectSprintTaskSnapshotRead
     */
    description: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectSprintTaskSnapshotRead
     */
    acceptanceCriteria: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectSprintTaskSnapshotRead
     */
    tag: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectSprintTaskSnapshotRead
     */
    liveTaskExists?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ProjectSprintTaskSnapshotRead
     */
    createdAt: Date | null;
}

/**
 * Check if a given object implements the ProjectSprintTaskSnapshotRead interface.
 */
export function instanceOfProjectSprintTaskSnapshotRead(value: object): value is ProjectSprintTaskSnapshotRead {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('sprintId' in value) || value['sprintId'] === undefined) return false;
    if (!('taskId' in value) || value['taskId'] === undefined) return false;
    if (!('columnId' in value) || value['columnId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('outcome' in value) || value['outcome'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    if (!('storyPoints' in value) || value['storyPoints'] === undefined) return false;
    if (!('rank' in value) || value['rank'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('acceptanceCriteria' in value) || value['acceptanceCriteria'] === undefined) return false;
    if (!('tag' in value) || value['tag'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ProjectSprintTaskSnapshotReadFromJSON(json: any): ProjectSprintTaskSnapshotRead {
    return ProjectSprintTaskSnapshotReadFromJSONTyped(json, false);
}

export function ProjectSprintTaskSnapshotReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectSprintTaskSnapshotRead {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'sprintId': json['sprint_id'],
        'taskId': json['task_id'],
        'columnId': json['column_id'],
        'title': json['title'],
        'outcome': json['outcome'],
        'priority': json['priority'],
        'storyPoints': json['story_points'],
        'rank': json['rank'],
        'description': json['description'],
        'acceptanceCriteria': json['acceptance_criteria'],
        'tag': json['tag'],
        'liveTaskExists': json['live_task_exists'] == null ? undefined : json['live_task_exists'],
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
    };
}

export function ProjectSprintTaskSnapshotReadToJSON(json: any): ProjectSprintTaskSnapshotRead {
    return ProjectSprintTaskSnapshotReadToJSONTyped(json, false);
}

export function ProjectSprintTaskSnapshotReadToJSONTyped(value?: ProjectSprintTaskSnapshotRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'sprint_id': value['sprintId'],
        'task_id': value['taskId'],
        'column_id': value['columnId'],
        'title': value['title'],
        'outcome': value['outcome'],
        'priority': value['priority'],
        'story_points': value['storyPoints'],
        'rank': value['rank'],
        'description': value['description'],
        'acceptance_criteria': value['acceptanceCriteria'],
        'tag': value['tag'],
        'live_task_exists': value['liveTaskExists'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

