// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectDashboardCardRead } from './ProjectDashboardCardRead';
import {
    ProjectDashboardCardReadFromJSON,
    ProjectDashboardCardReadFromJSONTyped,
    ProjectDashboardCardReadToJSON,
    ProjectDashboardCardReadToJSONTyped,
} from './ProjectDashboardCardRead';

/**
 * Aggregated Project Dashboard payload.
 * @export
 * @interface ProjectDashboardRead
 */
export interface ProjectDashboardRead {
    /**
     * 
     * @type {string}
     * @memberof ProjectDashboardRead
     */
    projectId: string;
    /**
     * 
     * @type {Date}
     * @memberof ProjectDashboardRead
     */
    generatedAt: Date;
    /**
     * 
     * @type {Array<ProjectDashboardCardRead>}
     * @memberof ProjectDashboardRead
     */
    charts: Array<ProjectDashboardCardRead>;
}

/**
 * Check if a given object implements the ProjectDashboardRead interface.
 */
export function instanceOfProjectDashboardRead(value: object): value is ProjectDashboardRead {
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('generatedAt' in value) || value['generatedAt'] === undefined) return false;
    if (!('charts' in value) || value['charts'] === undefined) return false;
    return true;
}

export function ProjectDashboardReadFromJSON(json: any): ProjectDashboardRead {
    return ProjectDashboardReadFromJSONTyped(json, false);
}

export function ProjectDashboardReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDashboardRead {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'generatedAt': (new Date(json['generated_at'])),
        'charts': ((json['charts'] as Array<any>).map(ProjectDashboardCardReadFromJSON)),
    };
}

export function ProjectDashboardReadToJSON(json: any): ProjectDashboardRead {
    return ProjectDashboardReadToJSONTyped(json, false);
}

export function ProjectDashboardReadToJSONTyped(value?: ProjectDashboardRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'generated_at': value['generatedAt'].toISOString(),
        'charts': ((value['charts'] as Array<any>).map(ProjectDashboardCardReadToJSON)),
    };
}

