// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectSprintRead } from './ProjectSprintRead';
import {
    ProjectSprintReadFromJSON,
    ProjectSprintReadFromJSONTyped,
    ProjectSprintReadToJSON,
    ProjectSprintReadToJSONTyped,
} from './ProjectSprintRead';
import type { ProjectSprintTaskSnapshotRead } from './ProjectSprintTaskSnapshotRead';
import {
    ProjectSprintTaskSnapshotReadFromJSON,
    ProjectSprintTaskSnapshotReadFromJSONTyped,
    ProjectSprintTaskSnapshotReadToJSON,
    ProjectSprintTaskSnapshotReadToJSONTyped,
} from './ProjectSprintTaskSnapshotRead';

/**
 * Closed sprint summary and historical task detail.
 * @export
 * @interface ProjectSprintHistoryRead
 */
export interface ProjectSprintHistoryRead {
    /**
     * 
     * @type {ProjectSprintRead}
     * @memberof ProjectSprintHistoryRead
     */
    sprint: ProjectSprintRead;
    /**
     * 
     * @type {number}
     * @memberof ProjectSprintHistoryRead
     */
    finishedCount: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectSprintHistoryRead
     */
    unfinishedCount: number;
    /**
     * 
     * @type {Array<ProjectSprintTaskSnapshotRead>}
     * @memberof ProjectSprintHistoryRead
     */
    snapshots: Array<ProjectSprintTaskSnapshotRead>;
}

/**
 * Check if a given object implements the ProjectSprintHistoryRead interface.
 */
export function instanceOfProjectSprintHistoryRead(value: object): value is ProjectSprintHistoryRead {
    if (!('sprint' in value) || value['sprint'] === undefined) return false;
    if (!('finishedCount' in value) || value['finishedCount'] === undefined) return false;
    if (!('unfinishedCount' in value) || value['unfinishedCount'] === undefined) return false;
    if (!('snapshots' in value) || value['snapshots'] === undefined) return false;
    return true;
}

export function ProjectSprintHistoryReadFromJSON(json: any): ProjectSprintHistoryRead {
    return ProjectSprintHistoryReadFromJSONTyped(json, false);
}

export function ProjectSprintHistoryReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectSprintHistoryRead {
    if (json == null) {
        return json;
    }
    return {
        
        'sprint': ProjectSprintReadFromJSON(json['sprint']),
        'finishedCount': json['finished_count'],
        'unfinishedCount': json['unfinished_count'],
        'snapshots': ((json['snapshots'] as Array<any>).map(ProjectSprintTaskSnapshotReadFromJSON)),
    };
}

export function ProjectSprintHistoryReadToJSON(json: any): ProjectSprintHistoryRead {
    return ProjectSprintHistoryReadToJSONTyped(json, false);
}

export function ProjectSprintHistoryReadToJSONTyped(value?: ProjectSprintHistoryRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sprint': ProjectSprintReadToJSON(value['sprint']),
        'finished_count': value['finishedCount'],
        'unfinished_count': value['unfinishedCount'],
        'snapshots': ((value['snapshots'] as Array<any>).map(ProjectSprintTaskSnapshotReadToJSON)),
    };
}

