// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request payload for adding a project member.
 * @export
 * @interface ProjectMemberCreate
 */
export interface ProjectMemberCreate {
    /**
     * 
     * @type {string}
     * @memberof ProjectMemberCreate
     */
    userId: string;
}

/**
 * Check if a given object implements the ProjectMemberCreate interface.
 */
export function instanceOfProjectMemberCreate(value: object): value is ProjectMemberCreate {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function ProjectMemberCreateFromJSON(json: any): ProjectMemberCreate {
    return ProjectMemberCreateFromJSONTyped(json, false);
}

export function ProjectMemberCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectMemberCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
    };
}

export function ProjectMemberCreateToJSON(json: any): ProjectMemberCreate {
    return ProjectMemberCreateToJSONTyped(json, false);
}

export function ProjectMemberCreateToJSONTyped(value?: ProjectMemberCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
    };
}

