// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectSprintRead } from './ProjectSprintRead';
import {
    ProjectSprintReadFromJSON,
    ProjectSprintReadFromJSONTyped,
    ProjectSprintReadToJSON,
    ProjectSprintReadToJSONTyped,
} from './ProjectSprintRead';
import type { TaskRead } from './TaskRead';
import {
    TaskReadFromJSON,
    TaskReadFromJSONTyped,
    TaskReadToJSON,
    TaskReadToJSONTyped,
} from './TaskRead';

/**
 * Confirmation payload for closing an active sprint.
 * @export
 * @interface ProjectSprintClosePreviewRead
 */
export interface ProjectSprintClosePreviewRead {
    /**
     * 
     * @type {ProjectSprintRead}
     * @memberof ProjectSprintClosePreviewRead
     */
    sprint: ProjectSprintRead;
    /**
     * 
     * @type {number}
     * @memberof ProjectSprintClosePreviewRead
     */
    finishedCount: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectSprintClosePreviewRead
     */
    unfinishedCount: number;
    /**
     * 
     * @type {Array<TaskRead>}
     * @memberof ProjectSprintClosePreviewRead
     */
    unfinishedTasks: Array<TaskRead>;
    /**
     * 
     * @type {string}
     * @memberof ProjectSprintClosePreviewRead
     */
    carryoverStatement: string;
}

/**
 * Check if a given object implements the ProjectSprintClosePreviewRead interface.
 */
export function instanceOfProjectSprintClosePreviewRead(value: object): value is ProjectSprintClosePreviewRead {
    if (!('sprint' in value) || value['sprint'] === undefined) return false;
    if (!('finishedCount' in value) || value['finishedCount'] === undefined) return false;
    if (!('unfinishedCount' in value) || value['unfinishedCount'] === undefined) return false;
    if (!('unfinishedTasks' in value) || value['unfinishedTasks'] === undefined) return false;
    if (!('carryoverStatement' in value) || value['carryoverStatement'] === undefined) return false;
    return true;
}

export function ProjectSprintClosePreviewReadFromJSON(json: any): ProjectSprintClosePreviewRead {
    return ProjectSprintClosePreviewReadFromJSONTyped(json, false);
}

export function ProjectSprintClosePreviewReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectSprintClosePreviewRead {
    if (json == null) {
        return json;
    }
    return {
        
        'sprint': ProjectSprintReadFromJSON(json['sprint']),
        'finishedCount': json['finished_count'],
        'unfinishedCount': json['unfinished_count'],
        'unfinishedTasks': ((json['unfinished_tasks'] as Array<any>).map(TaskReadFromJSON)),
        'carryoverStatement': json['carryover_statement'],
    };
}

export function ProjectSprintClosePreviewReadToJSON(json: any): ProjectSprintClosePreviewRead {
    return ProjectSprintClosePreviewReadToJSONTyped(json, false);
}

export function ProjectSprintClosePreviewReadToJSONTyped(value?: ProjectSprintClosePreviewRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sprint': ProjectSprintReadToJSON(value['sprint']),
        'finished_count': value['finishedCount'],
        'unfinished_count': value['unfinishedCount'],
        'unfinished_tasks': ((value['unfinishedTasks'] as Array<any>).map(TaskReadToJSON)),
        'carryover_statement': value['carryoverStatement'],
    };
}

