// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectChatAuthorRead } from './ProjectChatAuthorRead';
import {
    ProjectChatAuthorReadFromJSON,
    ProjectChatAuthorReadFromJSONTyped,
    ProjectChatAuthorReadToJSON,
    ProjectChatAuthorReadToJSONTyped,
} from './ProjectChatAuthorRead';

/**
 * Project chat history message response payload.
 * @export
 * @interface ProjectChatMessageRead
 */
export interface ProjectChatMessageRead {
    /**
     * 
     * @type {string}
     * @memberof ProjectChatMessageRead
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectChatMessageRead
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectChatMessageRead
     */
    body: string;
    /**
     * 
     * @type {Date}
     * @memberof ProjectChatMessageRead
     */
    createdAt: Date;
    /**
     * 
     * @type {ProjectChatAuthorRead}
     * @memberof ProjectChatMessageRead
     */
    author: ProjectChatAuthorRead;
}

/**
 * Check if a given object implements the ProjectChatMessageRead interface.
 */
export function instanceOfProjectChatMessageRead(value: object): value is ProjectChatMessageRead {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    return true;
}

export function ProjectChatMessageReadFromJSON(json: any): ProjectChatMessageRead {
    return ProjectChatMessageReadFromJSONTyped(json, false);
}

export function ProjectChatMessageReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectChatMessageRead {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'projectId': json['project_id'],
        'body': json['body'],
        'createdAt': (new Date(json['created_at'])),
        'author': ProjectChatAuthorReadFromJSON(json['author']),
    };
}

export function ProjectChatMessageReadToJSON(json: any): ProjectChatMessageRead {
    return ProjectChatMessageReadToJSONTyped(json, false);
}

export function ProjectChatMessageReadToJSONTyped(value?: ProjectChatMessageRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'project_id': value['projectId'],
        'body': value['body'],
        'created_at': value['createdAt'].toISOString(),
        'author': ProjectChatAuthorReadToJSON(value['author']),
    };
}

