// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request payload for updating a project workflow column.
 * @export
 * @interface ProjectColumnUpdate
 */
export interface ProjectColumnUpdate {
    /**
     * 
     * @type {string}
     * @memberof ProjectColumnUpdate
     */
    name: string;
}

/**
 * Check if a given object implements the ProjectColumnUpdate interface.
 */
export function instanceOfProjectColumnUpdate(value: object): value is ProjectColumnUpdate {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ProjectColumnUpdateFromJSON(json: any): ProjectColumnUpdate {
    return ProjectColumnUpdateFromJSONTyped(json, false);
}

export function ProjectColumnUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectColumnUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function ProjectColumnUpdateToJSON(json: any): ProjectColumnUpdate {
    return ProjectColumnUpdateToJSONTyped(json, false);
}

export function ProjectColumnUpdateToJSONTyped(value?: ProjectColumnUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

