/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Defines the payload for updating a project.
 * 
 * Attributes:
 *     name: Optional updated project display name. Defaults to None.
 *     code: Optional updated three-character project code using uppercase letters
 *         or digits. Defaults to None.
 *     priority: Optional updated project priority label. Defaults to None.
 *     description: Optional updated project description. Defaults to None.
 *     status: Optional updated project status label. Defaults to None.
 *     owner_ids: Optional replacement list of owner user IDs. Defaults to None.
 *     member_ids: Optional replacement list of member user IDs. Defaults to None.
 * @export
 * @interface ProjectUpdate
 */
export interface ProjectUpdate {
    /**
     * 
     * @type {string}
     * @memberof ProjectUpdate
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectUpdate
     */
    code?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectUpdate
     */
    priority?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectUpdate
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectUpdate
     */
    status?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectUpdate
     */
    ownerIds?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectUpdate
     */
    memberIds?: Array<string> | null;
}

/**
 * Check if a given object implements the ProjectUpdate interface.
 */
export function instanceOfProjectUpdate(value: object): value is ProjectUpdate {
    return true;
}

export function ProjectUpdateFromJSON(json: any): ProjectUpdate {
    return ProjectUpdateFromJSONTyped(json, false);
}

export function ProjectUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'code': json['code'] == null ? undefined : json['code'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': json['status'] == null ? undefined : json['status'],
        'ownerIds': json['owner_ids'] == null ? undefined : json['owner_ids'],
        'memberIds': json['member_ids'] == null ? undefined : json['member_ids'],
    };
}

export function ProjectUpdateToJSON(json: any): ProjectUpdate {
    return ProjectUpdateToJSONTyped(json, false);
}

export function ProjectUpdateToJSONTyped(value?: ProjectUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'code': value['code'],
        'priority': value['priority'],
        'description': value['description'],
        'status': value['status'],
        'owner_ids': value['ownerIds'],
        'member_ids': value['memberIds'],
    };
}

