// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Defines the payload for creating a project.
 * 
 * Attributes:
 *     name: Project display name.
 *     code: Three-character project code using uppercase letters or digits.
 *     priority: Project priority label.
 *     description: Optional project description. Defaults to None.
 *     status: Optional project status label. Defaults to None.
 *     owner_ids: User IDs assigned as project owners. Defaults to an empty list.
 *     member_ids: User IDs assigned as project members. Defaults to an empty list.
 * @export
 * @interface ProjectCreate
 */
export interface ProjectCreate {
    /**
     * 
     * @type {string}
     * @memberof ProjectCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreate
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreate
     */
    priority: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreate
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreate
     */
    status?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectCreate
     */
    ownerIds?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectCreate
     */
    memberIds?: Array<string>;
}

/**
 * Check if a given object implements the ProjectCreate interface.
 */
export function instanceOfProjectCreate(value: object): value is ProjectCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    return true;
}

export function ProjectCreateFromJSON(json: any): ProjectCreate {
    return ProjectCreateFromJSONTyped(json, false);
}

export function ProjectCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'code': json['code'],
        'priority': json['priority'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': json['status'] == null ? undefined : json['status'],
        'ownerIds': json['owner_ids'] == null ? undefined : json['owner_ids'],
        'memberIds': json['member_ids'] == null ? undefined : json['member_ids'],
    };
}

export function ProjectCreateToJSON(json: any): ProjectCreate {
    return ProjectCreateToJSONTyped(json, false);
}

export function ProjectCreateToJSONTyped(value?: ProjectCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'code': value['code'],
        'priority': value['priority'],
        'description': value['description'],
        'status': value['status'],
        'owner_ids': value['ownerIds'],
        'member_ids': value['memberIds'],
    };
}

