// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response payload for project Done Column configuration.
 * @export
 * @interface ProjectDoneColumnRead
 */
export interface ProjectDoneColumnRead {
    /**
     * 
     * @type {string}
     * @memberof ProjectDoneColumnRead
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDoneColumnRead
     */
    doneColumnId: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectDoneColumnRead
     */
    requiresDesignation: boolean;
}

/**
 * Check if a given object implements the ProjectDoneColumnRead interface.
 */
export function instanceOfProjectDoneColumnRead(value: object): value is ProjectDoneColumnRead {
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('doneColumnId' in value) || value['doneColumnId'] === undefined) return false;
    if (!('requiresDesignation' in value) || value['requiresDesignation'] === undefined) return false;
    return true;
}

export function ProjectDoneColumnReadFromJSON(json: any): ProjectDoneColumnRead {
    return ProjectDoneColumnReadFromJSONTyped(json, false);
}

export function ProjectDoneColumnReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDoneColumnRead {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'doneColumnId': json['done_column_id'],
        'requiresDesignation': json['requires_designation'],
    };
}

export function ProjectDoneColumnReadToJSON(json: any): ProjectDoneColumnRead {
    return ProjectDoneColumnReadToJSONTyped(json, false);
}

export function ProjectDoneColumnReadToJSONTyped(value?: ProjectDoneColumnRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'done_column_id': value['doneColumnId'],
        'requires_designation': value['requiresDesignation'],
    };
}

