// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request payload for updating active project sprint metadata.
 * @export
 * @interface ProjectSprintUpdate
 */
export interface ProjectSprintUpdate {
    /**
     * 
     * @type {Date}
     * @memberof ProjectSprintUpdate
     */
    plannedStartDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ProjectSprintUpdate
     */
    plannedEndDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectSprintUpdate
     */
    goal?: string | null;
}

/**
 * Check if a given object implements the ProjectSprintUpdate interface.
 */
export function instanceOfProjectSprintUpdate(value: object): value is ProjectSprintUpdate {
    return true;
}

export function ProjectSprintUpdateFromJSON(json: any): ProjectSprintUpdate {
    return ProjectSprintUpdateFromJSONTyped(json, false);
}

export function ProjectSprintUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectSprintUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'plannedStartDate': json['planned_start_date'] == null ? undefined : (new Date(json['planned_start_date'])),
        'plannedEndDate': json['planned_end_date'] == null ? undefined : (new Date(json['planned_end_date'])),
        'goal': json['goal'] == null ? undefined : json['goal'],
    };
}

export function ProjectSprintUpdateToJSON(json: any): ProjectSprintUpdate {
    return ProjectSprintUpdateToJSONTyped(json, false);
}

export function ProjectSprintUpdateToJSONTyped(value?: ProjectSprintUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'planned_start_date': value['plannedStartDate'] == null ? value['plannedStartDate'] : value['plannedStartDate'].toISOString().substring(0,10),
        'planned_end_date': value['plannedEndDate'] == null ? value['plannedEndDate'] : value['plannedEndDate'].toISOString().substring(0,10),
        'goal': value['goal'],
    };
}

