// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectDashboardCardEntryRead } from './ProjectDashboardCardEntryRead';
import {
    ProjectDashboardCardEntryReadFromJSON,
    ProjectDashboardCardEntryReadFromJSONTyped,
    ProjectDashboardCardEntryReadToJSON,
    ProjectDashboardCardEntryReadToJSONTyped,
} from './ProjectDashboardCardEntryRead';

/**
 * One chart-ready dashboard series.
 * @export
 * @interface ProjectDashboardSeriesRead
 */
export interface ProjectDashboardSeriesRead {
    /**
     * 
     * @type {string}
     * @memberof ProjectDashboardSeriesRead
     */
    name: string;
    /**
     * 
     * @type {Array<ProjectDashboardCardEntryRead>}
     * @memberof ProjectDashboardSeriesRead
     */
    entries?: Array<ProjectDashboardCardEntryRead>;
}

/**
 * Check if a given object implements the ProjectDashboardSeriesRead interface.
 */
export function instanceOfProjectDashboardSeriesRead(value: object): value is ProjectDashboardSeriesRead {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ProjectDashboardSeriesReadFromJSON(json: any): ProjectDashboardSeriesRead {
    return ProjectDashboardSeriesReadFromJSONTyped(json, false);
}

export function ProjectDashboardSeriesReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDashboardSeriesRead {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'entries': json['entries'] == null ? undefined : ((json['entries'] as Array<any>).map(ProjectDashboardCardEntryReadFromJSON)),
    };
}

export function ProjectDashboardSeriesReadToJSON(json: any): ProjectDashboardSeriesRead {
    return ProjectDashboardSeriesReadToJSONTyped(json, false);
}

export function ProjectDashboardSeriesReadToJSONTyped(value?: ProjectDashboardSeriesRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'entries': value['entries'] == null ? undefined : ((value['entries'] as Array<any>).map(ProjectDashboardCardEntryReadToJSON)),
    };
}

