// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValuesValue } from './ValuesValue';
import {
    ValuesValueFromJSON,
    ValuesValueFromJSONTyped,
    ValuesValueToJSON,
    ValuesValueToJSONTyped,
} from './ValuesValue';

/**
 * One chart-ready dashboard data entry.
 * @export
 * @interface ProjectDashboardCardEntryRead
 */
export interface ProjectDashboardCardEntryRead {
    /**
     * 
     * @type {string}
     * @memberof ProjectDashboardCardEntryRead
     */
    label: string;
    /**
     * 
     * @type {{ [key: string]: ValuesValue; }}
     * @memberof ProjectDashboardCardEntryRead
     */
    values?: { [key: string]: ValuesValue; };
}

/**
 * Check if a given object implements the ProjectDashboardCardEntryRead interface.
 */
export function instanceOfProjectDashboardCardEntryRead(value: object): value is ProjectDashboardCardEntryRead {
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function ProjectDashboardCardEntryReadFromJSON(json: any): ProjectDashboardCardEntryRead {
    return ProjectDashboardCardEntryReadFromJSONTyped(json, false);
}

export function ProjectDashboardCardEntryReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDashboardCardEntryRead {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'],
        'values': json['values'] == null ? undefined : (mapValues(json['values'], ValuesValueFromJSON)),
    };
}

export function ProjectDashboardCardEntryReadToJSON(json: any): ProjectDashboardCardEntryRead {
    return ProjectDashboardCardEntryReadToJSONTyped(json, false);
}

export function ProjectDashboardCardEntryReadToJSONTyped(value?: ProjectDashboardCardEntryRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'values': value['values'] == null ? undefined : (mapValues(value['values'], ValuesValueToJSON)),
    };
}

