// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectDashboardCardEmptyStateRead } from './ProjectDashboardCardEmptyStateRead';
import {
    ProjectDashboardCardEmptyStateReadFromJSON,
    ProjectDashboardCardEmptyStateReadFromJSONTyped,
    ProjectDashboardCardEmptyStateReadToJSON,
    ProjectDashboardCardEmptyStateReadToJSONTyped,
} from './ProjectDashboardCardEmptyStateRead';
import type { ProjectDashboardCardEntryRead } from './ProjectDashboardCardEntryRead';
import {
    ProjectDashboardCardEntryReadFromJSON,
    ProjectDashboardCardEntryReadFromJSONTyped,
    ProjectDashboardCardEntryReadToJSON,
    ProjectDashboardCardEntryReadToJSONTyped,
} from './ProjectDashboardCardEntryRead';
import type { ProjectDashboardSeriesRead } from './ProjectDashboardSeriesRead';
import {
    ProjectDashboardSeriesReadFromJSON,
    ProjectDashboardSeriesReadFromJSONTyped,
    ProjectDashboardSeriesReadToJSON,
    ProjectDashboardSeriesReadToJSONTyped,
} from './ProjectDashboardSeriesRead';

/**
 * One supported Project Dashboard chart card.
 * @export
 * @interface ProjectDashboardCardRead
 */
export interface ProjectDashboardCardRead {
    /**
     * 
     * @type {string}
     * @memberof ProjectDashboardCardRead
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDashboardCardRead
     */
    title: string;
    /**
     * 
     * @type {Array<ProjectDashboardSeriesRead>}
     * @memberof ProjectDashboardCardRead
     */
    series?: Array<ProjectDashboardSeriesRead>;
    /**
     * 
     * @type {Array<ProjectDashboardCardEntryRead>}
     * @memberof ProjectDashboardCardRead
     */
    entries?: Array<ProjectDashboardCardEntryRead>;
    /**
     * 
     * @type {ProjectDashboardCardEmptyStateRead}
     * @memberof ProjectDashboardCardRead
     */
    emptyState?: ProjectDashboardCardEmptyStateRead | null;
}

/**
 * Check if a given object implements the ProjectDashboardCardRead interface.
 */
export function instanceOfProjectDashboardCardRead(value: object): value is ProjectDashboardCardRead {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function ProjectDashboardCardReadFromJSON(json: any): ProjectDashboardCardRead {
    return ProjectDashboardCardReadFromJSONTyped(json, false);
}

export function ProjectDashboardCardReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDashboardCardRead {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'title': json['title'],
        'series': json['series'] == null ? undefined : ((json['series'] as Array<any>).map(ProjectDashboardSeriesReadFromJSON)),
        'entries': json['entries'] == null ? undefined : ((json['entries'] as Array<any>).map(ProjectDashboardCardEntryReadFromJSON)),
        'emptyState': json['empty_state'] == null ? undefined : ProjectDashboardCardEmptyStateReadFromJSON(json['empty_state']),
    };
}

export function ProjectDashboardCardReadToJSON(json: any): ProjectDashboardCardRead {
    return ProjectDashboardCardReadToJSONTyped(json, false);
}

export function ProjectDashboardCardReadToJSONTyped(value?: ProjectDashboardCardRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'title': value['title'],
        'series': value['series'] == null ? undefined : ((value['series'] as Array<any>).map(ProjectDashboardSeriesReadToJSON)),
        'entries': value['entries'] == null ? undefined : ((value['entries'] as Array<any>).map(ProjectDashboardCardEntryReadToJSON)),
        'empty_state': ProjectDashboardCardEmptyStateReadToJSON(value['emptyState']),
    };
}

