// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Small author payload embedded in chat messages.
 * @export
 * @interface ProjectChatAuthorRead
 */
export interface ProjectChatAuthorRead {
    /**
     * 
     * @type {string}
     * @memberof ProjectChatAuthorRead
     */
    id: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectChatAuthorRead
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectChatAuthorRead
     */
    initials: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectChatAuthorRead
     */
    deleted?: boolean;
}

/**
 * Check if a given object implements the ProjectChatAuthorRead interface.
 */
export function instanceOfProjectChatAuthorRead(value: object): value is ProjectChatAuthorRead {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('initials' in value) || value['initials'] === undefined) return false;
    return true;
}

export function ProjectChatAuthorReadFromJSON(json: any): ProjectChatAuthorRead {
    return ProjectChatAuthorReadFromJSONTyped(json, false);
}

export function ProjectChatAuthorReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectChatAuthorRead {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'displayName': json['display_name'],
        'initials': json['initials'],
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
    };
}

export function ProjectChatAuthorReadToJSON(json: any): ProjectChatAuthorRead {
    return ProjectChatAuthorReadToJSONTyped(json, false);
}

export function ProjectChatAuthorReadToJSONTyped(value?: ProjectChatAuthorRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'display_name': value['displayName'],
        'initials': value['initials'],
        'deleted': value['deleted'],
    };
}

