// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request payload for changing a project's Done Column.
 * @export
 * @interface ProjectDoneColumnUpdate
 */
export interface ProjectDoneColumnUpdate {
    /**
     * 
     * @type {string}
     * @memberof ProjectDoneColumnUpdate
     */
    doneColumnId: string;
}

/**
 * Check if a given object implements the ProjectDoneColumnUpdate interface.
 */
export function instanceOfProjectDoneColumnUpdate(value: object): value is ProjectDoneColumnUpdate {
    if (!('doneColumnId' in value) || value['doneColumnId'] === undefined) return false;
    return true;
}

export function ProjectDoneColumnUpdateFromJSON(json: any): ProjectDoneColumnUpdate {
    return ProjectDoneColumnUpdateFromJSONTyped(json, false);
}

export function ProjectDoneColumnUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDoneColumnUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'doneColumnId': json['done_column_id'],
    };
}

export function ProjectDoneColumnUpdateToJSON(json: any): ProjectDoneColumnUpdate {
    return ProjectDoneColumnUpdateToJSONTyped(json, false);
}

export function ProjectDoneColumnUpdateToJSONTyped(value?: ProjectDoneColumnUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'done_column_id': value['doneColumnId'],
    };
}

