// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request payload for creating a project task.
 * 
 * Parameters:
 *     title: Task title.
 *     status: Workflow status for the task. Defaults to "todo".
 *     priority: Priority level for the task. Defaults to "medium".
 *     assignee_id: Optional user ID assigned to the task.
 *     description: Optional task details.
 *     acceptance_criteria: Optional criteria required to complete the task.
 *     tag: Optional task tag.
 * @export
 * @interface TaskCreate
 */
export interface TaskCreate {
    /**
     * 
     * @type {string}
     * @memberof TaskCreate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof TaskCreate
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskCreate
     */
    priority?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskCreate
     */
    assigneeId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TaskCreate
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TaskCreate
     */
    acceptanceCriteria?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TaskCreate
     */
    tag?: string | null;
}

/**
 * Check if a given object implements the TaskCreate interface.
 */
export function instanceOfTaskCreate(value: object): value is TaskCreate {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function TaskCreateFromJSON(json: any): TaskCreate {
    return TaskCreateFromJSONTyped(json, false);
}

export function TaskCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'status': json['status'] == null ? undefined : json['status'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'assigneeId': json['assignee_id'] == null ? undefined : json['assignee_id'],
        'description': json['description'] == null ? undefined : json['description'],
        'acceptanceCriteria': json['acceptance_criteria'] == null ? undefined : json['acceptance_criteria'],
        'tag': json['tag'] == null ? undefined : json['tag'],
    };
}

export function TaskCreateToJSON(json: any): TaskCreate {
    return TaskCreateToJSONTyped(json, false);
}

export function TaskCreateToJSONTyped(value?: TaskCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'status': value['status'],
        'priority': value['priority'],
        'assignee_id': value['assigneeId'],
        'description': value['description'],
        'acceptance_criteria': value['acceptanceCriteria'],
        'tag': value['tag'],
    };
}

