/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request payload for updating a project task.
 * 
 * Parameters:
 *     title: Optional replacement task title.
 *     status: Optional replacement workflow status.
 *     priority: Optional replacement priority level.
 *     assignee_id: Optional replacement user ID assigned to the task.
 *     description: Optional replacement task details.
 *     acceptance_criteria: Optional replacement completion criteria.
 *     tag: Optional replacement task tag.
 * @export
 * @interface TaskUpdate
 */
export interface TaskUpdate {
    /**
     * 
     * @type {string}
     * @memberof TaskUpdate
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TaskUpdate
     */
    status?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TaskUpdate
     */
    priority?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TaskUpdate
     */
    assigneeId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TaskUpdate
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TaskUpdate
     */
    acceptanceCriteria?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TaskUpdate
     */
    tag?: string | null;
}

/**
 * Check if a given object implements the TaskUpdate interface.
 */
export function instanceOfTaskUpdate(value: object): value is TaskUpdate {
    return true;
}

export function TaskUpdateFromJSON(json: any): TaskUpdate {
    return TaskUpdateFromJSONTyped(json, false);
}

export function TaskUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'status': json['status'] == null ? undefined : json['status'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'assigneeId': json['assignee_id'] == null ? undefined : json['assignee_id'],
        'description': json['description'] == null ? undefined : json['description'],
        'acceptanceCriteria': json['acceptance_criteria'] == null ? undefined : json['acceptance_criteria'],
        'tag': json['tag'] == null ? undefined : json['tag'],
    };
}

export function TaskUpdateToJSON(json: any): TaskUpdate {
    return TaskUpdateToJSONTyped(json, false);
}

export function TaskUpdateToJSONTyped(value?: TaskUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'status': value['status'],
        'priority': value['priority'],
        'assignee_id': value['assigneeId'],
        'description': value['description'],
        'acceptance_criteria': value['acceptanceCriteria'],
        'tag': value['tag'],
    };
}

