// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response payload for reading a project task.
 * 
 * Parameters:
 *     id: Task ID.
 *     project_id: ID of the project that owns the task.
 *     title: Task title.
 *     status: Workflow status for the task.
 *     priority: Priority level for the task.
 *     rank: Sortable LexoRank-style position within the task status column.
 *     assignee_id: Optional user ID assigned to the task.
 *     description: Optional task details.
 *     acceptance_criteria: Optional criteria required to complete the task.
 *     tag: Optional task tag.
 *     created_at: Optional timestamp when the task was created.
 *     updated_at: Optional timestamp when the task was last updated.
 * @export
 * @interface TaskRead
 */
export interface TaskRead {
    /**
     * 
     * @type {string}
     * @memberof TaskRead
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TaskRead
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof TaskRead
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof TaskRead
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof TaskRead
     */
    priority: string;
    /**
     * 
     * @type {string}
     * @memberof TaskRead
     */
    rank: string;
    /**
     * 
     * @type {string}
     * @memberof TaskRead
     */
    assigneeId: string | null;
    /**
     * 
     * @type {string}
     * @memberof TaskRead
     */
    description: string | null;
    /**
     * 
     * @type {string}
     * @memberof TaskRead
     */
    acceptanceCriteria: string | null;
    /**
     * 
     * @type {string}
     * @memberof TaskRead
     */
    tag: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TaskRead
     */
    createdAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof TaskRead
     */
    updatedAt: Date | null;
}

/**
 * Check if a given object implements the TaskRead interface.
 */
export function instanceOfTaskRead(value: object): value is TaskRead {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    if (!('rank' in value) || value['rank'] === undefined) return false;
    if (!('assigneeId' in value) || value['assigneeId'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('acceptanceCriteria' in value) || value['acceptanceCriteria'] === undefined) return false;
    if (!('tag' in value) || value['tag'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function TaskReadFromJSON(json: any): TaskRead {
    return TaskReadFromJSONTyped(json, false);
}

export function TaskReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskRead {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'projectId': json['project_id'],
        'title': json['title'],
        'status': json['status'],
        'priority': json['priority'],
        'rank': json['rank'],
        'assigneeId': json['assignee_id'],
        'description': json['description'],
        'acceptanceCriteria': json['acceptance_criteria'],
        'tag': json['tag'],
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'updatedAt': (json['updated_at'] == null ? null : new Date(json['updated_at'])),
    };
}

export function TaskReadToJSON(json: any): TaskRead {
    return TaskReadToJSONTyped(json, false);
}

export function TaskReadToJSONTyped(value?: TaskRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'project_id': value['projectId'],
        'title': value['title'],
        'status': value['status'],
        'priority': value['priority'],
        'rank': value['rank'],
        'assignee_id': value['assigneeId'],
        'description': value['description'],
        'acceptance_criteria': value['acceptanceCriteria'],
        'tag': value['tag'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

