// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Destination for moving a task on the project board.
 * @export
 * @interface TaskDestination
 */
export interface TaskDestination {
    /**
     * 
     * @type {string}
     * @memberof TaskDestination
     */
    columnId: string;
    /**
     * 
     * @type {string}
     * @memberof TaskDestination
     */
    beforeTaskId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TaskDestination
     */
    afterTaskId?: string | null;
}

/**
 * Check if a given object implements the TaskDestination interface.
 */
export function instanceOfTaskDestination(value: object): value is TaskDestination {
    if (!('columnId' in value) || value['columnId'] === undefined) return false;
    return true;
}

export function TaskDestinationFromJSON(json: any): TaskDestination {
    return TaskDestinationFromJSONTyped(json, false);
}

export function TaskDestinationFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskDestination {
    if (json == null) {
        return json;
    }
    return {
        
        'columnId': json['column_id'],
        'beforeTaskId': json['before_task_id'] == null ? undefined : json['before_task_id'],
        'afterTaskId': json['after_task_id'] == null ? undefined : json['after_task_id'],
    };
}

export function TaskDestinationToJSON(json: any): TaskDestination {
    return TaskDestinationToJSONTyped(json, false);
}

export function TaskDestinationToJSONTyped(value?: TaskDestination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'column_id': value['columnId'],
        'before_task_id': value['beforeTaskId'],
        'after_task_id': value['afterTaskId'],
    };
}

