// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request payload for updating a project task.
 * 
 * Parameters:
 *     title: Optional replacement task title.
 *     column_id: Optional replacement workflow column ID.
 *     priority: Optional replacement priority level. Explicit null clears it.
 *     story_points: Optional replacement Story Points estimate. Explicit null clears it.
 *     assignee_id: Optional replacement user ID assigned to the task.
 *     description: Optional replacement task details.
 *     acceptance_criteria: Optional replacement completion criteria.
 *     tag: Optional replacement task tag.
 *     is_blocked: Optional explicit Blocked Project Task marker.
 *     blocked_reason: Optional replacement blocked reason. Explicit null clears it.
 * @export
 * @interface TaskUpdate
 */
export interface TaskUpdate {
    /**
     * 
     * @type {string}
     * @memberof TaskUpdate
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TaskUpdate
     */
    columnId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TaskUpdate
     */
    priority?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TaskUpdate
     */
    storyPoints?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TaskUpdate
     */
    assigneeId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TaskUpdate
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TaskUpdate
     */
    acceptanceCriteria?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TaskUpdate
     */
    tag?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof TaskUpdate
     */
    isBlocked?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof TaskUpdate
     */
    blockedReason?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof TaskUpdate
     */
    prerequisiteTaskIds?: Array<string>;
}

/**
 * Check if a given object implements the TaskUpdate interface.
 */
export function instanceOfTaskUpdate(value: object): value is TaskUpdate {
    return true;
}

export function TaskUpdateFromJSON(json: any): TaskUpdate {
    return TaskUpdateFromJSONTyped(json, false);
}

export function TaskUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'columnId': json['column_id'] == null ? undefined : json['column_id'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'storyPoints': json['story_points'] == null ? undefined : json['story_points'],
        'assigneeId': json['assignee_id'] == null ? undefined : json['assignee_id'],
        'description': json['description'] == null ? undefined : json['description'],
        'acceptanceCriteria': json['acceptance_criteria'] == null ? undefined : json['acceptance_criteria'],
        'tag': json['tag'] == null ? undefined : json['tag'],
        'isBlocked': json['is_blocked'] == null ? undefined : json['is_blocked'],
        'blockedReason': json['blocked_reason'] == null ? undefined : json['blocked_reason'],
        'prerequisiteTaskIds': json['prerequisite_task_ids'] == null ? undefined : json['prerequisite_task_ids'],
    };
}

export function TaskUpdateToJSON(json: any): TaskUpdate {
    return TaskUpdateToJSONTyped(json, false);
}

export function TaskUpdateToJSONTyped(value?: TaskUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'column_id': value['columnId'],
        'priority': value['priority'],
        'story_points': value['storyPoints'],
        'assignee_id': value['assigneeId'],
        'description': value['description'],
        'acceptance_criteria': value['acceptanceCriteria'],
        'tag': value['tag'],
        'is_blocked': value['isBlocked'],
        'blocked_reason': value['blockedReason'],
        'prerequisite_task_ids': value['prerequisiteTaskIds'],
    };
}

