// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Reviewed draft prerequisite reference.
 * @export
 * @interface TaskPrerequisiteRef
 */
export interface TaskPrerequisiteRef {
    /**
     * 
     * @type {TaskPrerequisiteRefTypeEnum}
     * @memberof TaskPrerequisiteRef
     */
    type: TaskPrerequisiteRefTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof TaskPrerequisiteRef
     */
    key?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TaskPrerequisiteRef
     */
    taskId?: string | null;
}


/**
 * @export
 */
export const TaskPrerequisiteRefTypeEnum = {
    Draft: 'draft',
    Existing: 'existing'
} as const;
export type TaskPrerequisiteRefTypeEnum = typeof TaskPrerequisiteRefTypeEnum[keyof typeof TaskPrerequisiteRefTypeEnum];


/**
 * Check if a given object implements the TaskPrerequisiteRef interface.
 */
export function instanceOfTaskPrerequisiteRef(value: object): value is TaskPrerequisiteRef {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function TaskPrerequisiteRefFromJSON(json: any): TaskPrerequisiteRef {
    return TaskPrerequisiteRefFromJSONTyped(json, false);
}

export function TaskPrerequisiteRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskPrerequisiteRef {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'key': json['key'] == null ? undefined : json['key'],
        'taskId': json['task_id'] == null ? undefined : json['task_id'],
    };
}

export function TaskPrerequisiteRefToJSON(json: any): TaskPrerequisiteRef {
    return TaskPrerequisiteRefToJSONTyped(json, false);
}

export function TaskPrerequisiteRefToJSONTyped(value?: TaskPrerequisiteRef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'key': value['key'],
        'task_id': value['taskId'],
    };
}

