// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValuesValue
 */
export interface ValuesValue {
}

/**
 * Check if a given object implements the ValuesValue interface.
 */
export function instanceOfValuesValue(value: object): value is ValuesValue {
    return true;
}

export function ValuesValueFromJSON(json: any): ValuesValue {
    return ValuesValueFromJSONTyped(json, false);
}

export function ValuesValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValuesValue {
    return json;
}

export function ValuesValueToJSON(json: any): ValuesValue {
    return ValuesValueToJSONTyped(json, false);
}

export function ValuesValueToJSONTyped(value?: ValuesValue | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

