// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface GetAgentCardA2aAgentSlugWellKnownAgentCardJsonGetRequest {
    agentSlug: string;
}

export interface InvokeAgentA2aAgentSlugPostRequest {
    agentSlug: string;
}

/**
 * 
 */
export class A2aApi extends runtime.BaseAPI {

    /**
     * Creates request options for getAgentCardA2aAgentSlugWellKnownAgentCardJsonGet without sending the request
     */
    async getAgentCardA2aAgentSlugWellKnownAgentCardJsonGetRequestOpts(requestParameters: GetAgentCardA2aAgentSlugWellKnownAgentCardJsonGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['agentSlug'] == null) {
            throw new runtime.RequiredError(
                'agentSlug',
                'Required parameter "agentSlug" was null or undefined when calling getAgentCardA2aAgentSlugWellKnownAgentCardJsonGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/a2a/{agent_slug}/.well-known/agent-card.json`;
        urlPath = urlPath.replace(`{${"agent_slug"}}`, encodeURIComponent(String(requestParameters['agentSlug'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return the public A2A agent card for a known agent slug.
     * Get Agent Card
     */
    async getAgentCardA2aAgentSlugWellKnownAgentCardJsonGetRaw(requestParameters: GetAgentCardA2aAgentSlugWellKnownAgentCardJsonGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.getAgentCardA2aAgentSlugWellKnownAgentCardJsonGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Return the public A2A agent card for a known agent slug.
     * Get Agent Card
     */
    async getAgentCardA2aAgentSlugWellKnownAgentCardJsonGet(requestParameters: GetAgentCardA2aAgentSlugWellKnownAgentCardJsonGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getAgentCardA2aAgentSlugWellKnownAgentCardJsonGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for invokeAgentA2aAgentSlugPost without sending the request
     */
    async invokeAgentA2aAgentSlugPostRequestOpts(requestParameters: InvokeAgentA2aAgentSlugPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['agentSlug'] == null) {
            throw new runtime.RequiredError(
                'agentSlug',
                'Required parameter "agentSlug" was null or undefined when calling invokeAgentA2aAgentSlugPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/a2a/{agent_slug}`;
        urlPath = urlPath.replace(`{${"agent_slug"}}`, encodeURIComponent(String(requestParameters['agentSlug'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delegate Acceptance Criteria invocation to the A2A SDK JSON-RPC route.
     * Invoke Agent
     */
    async invokeAgentA2aAgentSlugPostRaw(requestParameters: InvokeAgentA2aAgentSlugPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.invokeAgentA2aAgentSlugPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delegate Acceptance Criteria invocation to the A2A SDK JSON-RPC route.
     * Invoke Agent
     */
    async invokeAgentA2aAgentSlugPost(requestParameters: InvokeAgentA2aAgentSlugPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.invokeAgentA2aAgentSlugPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
