// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  ProjectBacklogReorder,
  ProjectChatMessageRead,
  ProjectColumnCreate,
  ProjectColumnRead,
  ProjectColumnReorder,
  ProjectColumnUpdate,
  ProjectCreate,
  ProjectDoneColumnRead,
  ProjectDoneColumnUpdate,
  ProjectMemberCreate,
  ProjectRead,
  ProjectSprintClosePreviewRead,
  ProjectSprintCloseRead,
  ProjectSprintCreate,
  ProjectSprintHistoryRead,
  ProjectSprintRead,
  ProjectSprintTaskAdd,
  ProjectSprintUpdate,
  ProjectUpdate,
  TaskCreate,
  TaskDestination,
  TaskRead,
  TaskUpdate,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ProjectBacklogReorderFromJSON,
    ProjectBacklogReorderToJSON,
    ProjectChatMessageReadFromJSON,
    ProjectChatMessageReadToJSON,
    ProjectColumnCreateFromJSON,
    ProjectColumnCreateToJSON,
    ProjectColumnReadFromJSON,
    ProjectColumnReadToJSON,
    ProjectColumnReorderFromJSON,
    ProjectColumnReorderToJSON,
    ProjectColumnUpdateFromJSON,
    ProjectColumnUpdateToJSON,
    ProjectCreateFromJSON,
    ProjectCreateToJSON,
    ProjectDoneColumnReadFromJSON,
    ProjectDoneColumnReadToJSON,
    ProjectDoneColumnUpdateFromJSON,
    ProjectDoneColumnUpdateToJSON,
    ProjectMemberCreateFromJSON,
    ProjectMemberCreateToJSON,
    ProjectReadFromJSON,
    ProjectReadToJSON,
    ProjectSprintClosePreviewReadFromJSON,
    ProjectSprintClosePreviewReadToJSON,
    ProjectSprintCloseReadFromJSON,
    ProjectSprintCloseReadToJSON,
    ProjectSprintCreateFromJSON,
    ProjectSprintCreateToJSON,
    ProjectSprintHistoryReadFromJSON,
    ProjectSprintHistoryReadToJSON,
    ProjectSprintReadFromJSON,
    ProjectSprintReadToJSON,
    ProjectSprintTaskAddFromJSON,
    ProjectSprintTaskAddToJSON,
    ProjectSprintUpdateFromJSON,
    ProjectSprintUpdateToJSON,
    ProjectUpdateFromJSON,
    ProjectUpdateToJSON,
    TaskCreateFromJSON,
    TaskCreateToJSON,
    TaskDestinationFromJSON,
    TaskDestinationToJSON,
    TaskReadFromJSON,
    TaskReadToJSON,
    TaskUpdateFromJSON,
    TaskUpdateToJSON,
} from '../models/index';

export interface AddProjectMemberProjectsProjectIdMembersPostRequest {
    projectId: string;
    projectMemberCreate: ProjectMemberCreate;
}

export interface AddTaskToActiveProjectSprintProjectsProjectIdSprintsActiveTasksPostRequest {
    projectId: string;
    projectSprintTaskAdd: ProjectSprintTaskAdd;
}

export interface CloseActiveProjectSprintProjectsProjectIdSprintsActiveClosePostRequest {
    projectId: string;
}

export interface CreateProjectBacklogTaskProjectsProjectIdBacklogTasksPostRequest {
    projectId: string;
    taskCreate: TaskCreate;
}

export interface CreateProjectColumnProjectsProjectIdColumnsPostRequest {
    projectId: string;
    projectColumnCreate: ProjectColumnCreate;
}

export interface CreateProjectEndpointProjectsPostRequest {
    projectCreate: ProjectCreate;
}

export interface CreateProjectSprintProjectsProjectIdSprintsPostRequest {
    projectId: string;
    projectSprintCreate: ProjectSprintCreate;
}

export interface CreateTaskEndpointProjectsProjectIdTasksPostRequest {
    projectId: string;
    taskCreate: TaskCreate;
}

export interface DeleteProjectColumnProjectsProjectIdColumnsColumnIdDeleteRequest {
    projectId: string;
    columnId: string;
}

export interface DeleteProjectProjectsProjectIdDeleteRequest {
    projectId: string;
}

export interface DeleteTaskEndpointProjectsProjectIdTasksTaskIdDeleteRequest {
    projectId: string;
    taskId: string;
}

export interface GetActiveProjectSprintCloseConfirmationProjectsProjectIdSprintsActiveCloseConfirmationGetRequest {
    projectId: string;
}

export interface GetActiveProjectSprintProjectsProjectIdSprintsActiveGetRequest {
    projectId: string;
}

export interface GetProjectDoneColumnProjectsProjectIdDoneColumnGetRequest {
    projectId: string;
}

export interface GetProjectProjectsProjectIdGetRequest {
    projectId: string;
}

export interface GetTaskEndpointProjectsProjectIdTasksTaskIdGetRequest {
    projectId: string;
    taskId: string;
}

export interface ListActiveSprintTasksEndpointProjectsProjectIdTasksActiveSprintGetRequest {
    projectId: string;
}

export interface ListProjectBacklogProjectsProjectIdBacklogGetRequest {
    projectId: string;
}

export interface ListProjectChatMessagesProjectsProjectIdChatMessagesGetRequest {
    projectId: string;
    cursor?: string | null;
}

export interface ListProjectColumnsProjectsProjectIdColumnsGetRequest {
    projectId: string;
}

export interface ListProjectSprintHistoryProjectsProjectIdSprintsHistoryGetRequest {
    projectId: string;
}

export interface ListTasksEndpointProjectsProjectIdTasksGetRequest {
    projectId: string;
}

export interface MoveTaskEndpointProjectsProjectIdTasksTaskIdMovePutRequest {
    projectId: string;
    taskId: string;
    taskDestination: TaskDestination;
}

export interface RemoveTaskFromActiveProjectSprintProjectsProjectIdSprintsActiveTasksTaskIdDeleteRequest {
    projectId: string;
    taskId: string;
}

export interface ReorderProjectBacklogProjectsProjectIdBacklogReorderPutRequest {
    projectId: string;
    projectBacklogReorder: ProjectBacklogReorder;
}

export interface ReorderProjectColumnsProjectsProjectIdColumnsReorderPutRequest {
    projectId: string;
    projectColumnReorder: ProjectColumnReorder;
}

export interface UpdateActiveProjectSprintProjectsProjectIdSprintsActivePatchRequest {
    projectId: string;
    projectSprintUpdate: ProjectSprintUpdate;
}

export interface UpdateProjectColumnProjectsProjectIdColumnsColumnIdPatchRequest {
    projectId: string;
    columnId: string;
    projectColumnUpdate: ProjectColumnUpdate;
}

export interface UpdateProjectDoneColumnProjectsProjectIdDoneColumnPatchRequest {
    projectId: string;
    projectDoneColumnUpdate: ProjectDoneColumnUpdate;
}

export interface UpdateProjectProjectsProjectIdPatchRequest {
    projectId: string;
    projectUpdate: ProjectUpdate;
}

export interface UpdateTaskEndpointProjectsProjectIdTasksTaskIdPatchRequest {
    projectId: string;
    taskId: string;
    taskUpdate: TaskUpdate;
}

/**
 * 
 */
export class ProjectsApi extends runtime.BaseAPI {

    /**
     * Creates request options for addProjectMemberProjectsProjectIdMembersPost without sending the request
     */
    async addProjectMemberProjectsProjectIdMembersPostRequestOpts(requestParameters: AddProjectMemberProjectsProjectIdMembersPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling addProjectMemberProjectsProjectIdMembersPost().'
            );
        }

        if (requestParameters['projectMemberCreate'] == null) {
            throw new runtime.RequiredError(
                'projectMemberCreate',
                'Required parameter "projectMemberCreate" was null or undefined when calling addProjectMemberProjectsProjectIdMembersPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/projects/{project_id}/members`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectMemberCreateToJSON(requestParameters['projectMemberCreate']),
        };
    }

    /**
     * Add a member to a project owned by the current user.
     * Add Project Member
     */
    async addProjectMemberProjectsProjectIdMembersPostRaw(requestParameters: AddProjectMemberProjectsProjectIdMembersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectRead>> {
        const requestOptions = await this.addProjectMemberProjectsProjectIdMembersPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectReadFromJSON(jsonValue));
    }

    /**
     * Add a member to a project owned by the current user.
     * Add Project Member
     */
    async addProjectMemberProjectsProjectIdMembersPost(requestParameters: AddProjectMemberProjectsProjectIdMembersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectRead> {
        const response = await this.addProjectMemberProjectsProjectIdMembersPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for addTaskToActiveProjectSprintProjectsProjectIdSprintsActiveTasksPost without sending the request
     */
    async addTaskToActiveProjectSprintProjectsProjectIdSprintsActiveTasksPostRequestOpts(requestParameters: AddTaskToActiveProjectSprintProjectsProjectIdSprintsActiveTasksPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling addTaskToActiveProjectSprintProjectsProjectIdSprintsActiveTasksPost().'
            );
        }

        if (requestParameters['projectSprintTaskAdd'] == null) {
            throw new runtime.RequiredError(
                'projectSprintTaskAdd',
                'Required parameter "projectSprintTaskAdd" was null or undefined when calling addTaskToActiveProjectSprintProjectsProjectIdSprintsActiveTasksPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/projects/{project_id}/sprints/active/tasks`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectSprintTaskAddToJSON(requestParameters['projectSprintTaskAdd']),
        };
    }

    /**
     * Add an existing Backlog task to the active sprint.
     * Add Task To Active Project Sprint
     */
    async addTaskToActiveProjectSprintProjectsProjectIdSprintsActiveTasksPostRaw(requestParameters: AddTaskToActiveProjectSprintProjectsProjectIdSprintsActiveTasksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskRead>> {
        const requestOptions = await this.addTaskToActiveProjectSprintProjectsProjectIdSprintsActiveTasksPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskReadFromJSON(jsonValue));
    }

    /**
     * Add an existing Backlog task to the active sprint.
     * Add Task To Active Project Sprint
     */
    async addTaskToActiveProjectSprintProjectsProjectIdSprintsActiveTasksPost(requestParameters: AddTaskToActiveProjectSprintProjectsProjectIdSprintsActiveTasksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskRead> {
        const response = await this.addTaskToActiveProjectSprintProjectsProjectIdSprintsActiveTasksPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for closeActiveProjectSprintProjectsProjectIdSprintsActiveClosePost without sending the request
     */
    async closeActiveProjectSprintProjectsProjectIdSprintsActiveClosePostRequestOpts(requestParameters: CloseActiveProjectSprintProjectsProjectIdSprintsActiveClosePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling closeActiveProjectSprintProjectsProjectIdSprintsActiveClosePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects/{project_id}/sprints/active/close`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Close the active sprint and create immutable task history.
     * Close Active Project Sprint
     */
    async closeActiveProjectSprintProjectsProjectIdSprintsActiveClosePostRaw(requestParameters: CloseActiveProjectSprintProjectsProjectIdSprintsActiveClosePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectSprintCloseRead>> {
        const requestOptions = await this.closeActiveProjectSprintProjectsProjectIdSprintsActiveClosePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectSprintCloseReadFromJSON(jsonValue));
    }

    /**
     * Close the active sprint and create immutable task history.
     * Close Active Project Sprint
     */
    async closeActiveProjectSprintProjectsProjectIdSprintsActiveClosePost(requestParameters: CloseActiveProjectSprintProjectsProjectIdSprintsActiveClosePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectSprintCloseRead> {
        const response = await this.closeActiveProjectSprintProjectsProjectIdSprintsActiveClosePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createProjectBacklogTaskProjectsProjectIdBacklogTasksPost without sending the request
     */
    async createProjectBacklogTaskProjectsProjectIdBacklogTasksPostRequestOpts(requestParameters: CreateProjectBacklogTaskProjectsProjectIdBacklogTasksPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling createProjectBacklogTaskProjectsProjectIdBacklogTasksPost().'
            );
        }

        if (requestParameters['taskCreate'] == null) {
            throw new runtime.RequiredError(
                'taskCreate',
                'Required parameter "taskCreate" was null or undefined when calling createProjectBacklogTaskProjectsProjectIdBacklogTasksPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/projects/{project_id}/backlog/tasks`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TaskCreateToJSON(requestParameters['taskCreate']),
        };
    }

    /**
     * Create a task at the top of the project Backlog.
     * Create Project Backlog Task
     */
    async createProjectBacklogTaskProjectsProjectIdBacklogTasksPostRaw(requestParameters: CreateProjectBacklogTaskProjectsProjectIdBacklogTasksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskRead>> {
        const requestOptions = await this.createProjectBacklogTaskProjectsProjectIdBacklogTasksPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskReadFromJSON(jsonValue));
    }

    /**
     * Create a task at the top of the project Backlog.
     * Create Project Backlog Task
     */
    async createProjectBacklogTaskProjectsProjectIdBacklogTasksPost(requestParameters: CreateProjectBacklogTaskProjectsProjectIdBacklogTasksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskRead> {
        const response = await this.createProjectBacklogTaskProjectsProjectIdBacklogTasksPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createProjectColumnProjectsProjectIdColumnsPost without sending the request
     */
    async createProjectColumnProjectsProjectIdColumnsPostRequestOpts(requestParameters: CreateProjectColumnProjectsProjectIdColumnsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling createProjectColumnProjectsProjectIdColumnsPost().'
            );
        }

        if (requestParameters['projectColumnCreate'] == null) {
            throw new runtime.RequiredError(
                'projectColumnCreate',
                'Required parameter "projectColumnCreate" was null or undefined when calling createProjectColumnProjectsProjectIdColumnsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/projects/{project_id}/columns`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectColumnCreateToJSON(requestParameters['projectColumnCreate']),
        };
    }

    /**
     * Create a workflow column for a project owned by the current user.
     * Create Project Column
     */
    async createProjectColumnProjectsProjectIdColumnsPostRaw(requestParameters: CreateProjectColumnProjectsProjectIdColumnsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectColumnRead>> {
        const requestOptions = await this.createProjectColumnProjectsProjectIdColumnsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectColumnReadFromJSON(jsonValue));
    }

    /**
     * Create a workflow column for a project owned by the current user.
     * Create Project Column
     */
    async createProjectColumnProjectsProjectIdColumnsPost(requestParameters: CreateProjectColumnProjectsProjectIdColumnsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectColumnRead> {
        const response = await this.createProjectColumnProjectsProjectIdColumnsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createProjectEndpointProjectsPost without sending the request
     */
    async createProjectEndpointProjectsPostRequestOpts(requestParameters: CreateProjectEndpointProjectsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectCreate'] == null) {
            throw new runtime.RequiredError(
                'projectCreate',
                'Required parameter "projectCreate" was null or undefined when calling createProjectEndpointProjectsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/projects`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectCreateToJSON(requestParameters['projectCreate']),
        };
    }

    /**
     * Create a project for the current user.
     * Create Project Endpoint
     */
    async createProjectEndpointProjectsPostRaw(requestParameters: CreateProjectEndpointProjectsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectRead>> {
        const requestOptions = await this.createProjectEndpointProjectsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectReadFromJSON(jsonValue));
    }

    /**
     * Create a project for the current user.
     * Create Project Endpoint
     */
    async createProjectEndpointProjectsPost(requestParameters: CreateProjectEndpointProjectsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectRead> {
        const response = await this.createProjectEndpointProjectsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createProjectSprintProjectsProjectIdSprintsPost without sending the request
     */
    async createProjectSprintProjectsProjectIdSprintsPostRequestOpts(requestParameters: CreateProjectSprintProjectsProjectIdSprintsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling createProjectSprintProjectsProjectIdSprintsPost().'
            );
        }

        if (requestParameters['projectSprintCreate'] == null) {
            throw new runtime.RequiredError(
                'projectSprintCreate',
                'Required parameter "projectSprintCreate" was null or undefined when calling createProjectSprintProjectsProjectIdSprintsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/projects/{project_id}/sprints`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectSprintCreateToJSON(requestParameters['projectSprintCreate']),
        };
    }

    /**
     * Create an empty active sprint for a project owned by the current user.
     * Create Project Sprint
     */
    async createProjectSprintProjectsProjectIdSprintsPostRaw(requestParameters: CreateProjectSprintProjectsProjectIdSprintsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectSprintRead>> {
        const requestOptions = await this.createProjectSprintProjectsProjectIdSprintsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectSprintReadFromJSON(jsonValue));
    }

    /**
     * Create an empty active sprint for a project owned by the current user.
     * Create Project Sprint
     */
    async createProjectSprintProjectsProjectIdSprintsPost(requestParameters: CreateProjectSprintProjectsProjectIdSprintsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectSprintRead> {
        const response = await this.createProjectSprintProjectsProjectIdSprintsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createTaskEndpointProjectsProjectIdTasksPost without sending the request
     */
    async createTaskEndpointProjectsProjectIdTasksPostRequestOpts(requestParameters: CreateTaskEndpointProjectsProjectIdTasksPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling createTaskEndpointProjectsProjectIdTasksPost().'
            );
        }

        if (requestParameters['taskCreate'] == null) {
            throw new runtime.RequiredError(
                'taskCreate',
                'Required parameter "taskCreate" was null or undefined when calling createTaskEndpointProjectsProjectIdTasksPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/projects/{project_id}/tasks`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TaskCreateToJSON(requestParameters['taskCreate']),
        };
    }

    /**
     * Create a task in a project accessible to the current user.
     * Create Task Endpoint
     */
    async createTaskEndpointProjectsProjectIdTasksPostRaw(requestParameters: CreateTaskEndpointProjectsProjectIdTasksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskRead>> {
        const requestOptions = await this.createTaskEndpointProjectsProjectIdTasksPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskReadFromJSON(jsonValue));
    }

    /**
     * Create a task in a project accessible to the current user.
     * Create Task Endpoint
     */
    async createTaskEndpointProjectsProjectIdTasksPost(requestParameters: CreateTaskEndpointProjectsProjectIdTasksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskRead> {
        const response = await this.createTaskEndpointProjectsProjectIdTasksPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteProjectColumnProjectsProjectIdColumnsColumnIdDelete without sending the request
     */
    async deleteProjectColumnProjectsProjectIdColumnsColumnIdDeleteRequestOpts(requestParameters: DeleteProjectColumnProjectsProjectIdColumnsColumnIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling deleteProjectColumnProjectsProjectIdColumnsColumnIdDelete().'
            );
        }

        if (requestParameters['columnId'] == null) {
            throw new runtime.RequiredError(
                'columnId',
                'Required parameter "columnId" was null or undefined when calling deleteProjectColumnProjectsProjectIdColumnsColumnIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects/{project_id}/columns/{column_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"column_id"}}`, encodeURIComponent(String(requestParameters['columnId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete an empty workflow column from a project owned by the current user.
     * Delete Project Column
     */
    async deleteProjectColumnProjectsProjectIdColumnsColumnIdDeleteRaw(requestParameters: DeleteProjectColumnProjectsProjectIdColumnsColumnIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteProjectColumnProjectsProjectIdColumnsColumnIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an empty workflow column from a project owned by the current user.
     * Delete Project Column
     */
    async deleteProjectColumnProjectsProjectIdColumnsColumnIdDelete(requestParameters: DeleteProjectColumnProjectsProjectIdColumnsColumnIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteProjectColumnProjectsProjectIdColumnsColumnIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteProjectProjectsProjectIdDelete without sending the request
     */
    async deleteProjectProjectsProjectIdDeleteRequestOpts(requestParameters: DeleteProjectProjectsProjectIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling deleteProjectProjectsProjectIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects/{project_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a project owned by the current user.
     * Delete Project
     */
    async deleteProjectProjectsProjectIdDeleteRaw(requestParameters: DeleteProjectProjectsProjectIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteProjectProjectsProjectIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a project owned by the current user.
     * Delete Project
     */
    async deleteProjectProjectsProjectIdDelete(requestParameters: DeleteProjectProjectsProjectIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteProjectProjectsProjectIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteTaskEndpointProjectsProjectIdTasksTaskIdDelete without sending the request
     */
    async deleteTaskEndpointProjectsProjectIdTasksTaskIdDeleteRequestOpts(requestParameters: DeleteTaskEndpointProjectsProjectIdTasksTaskIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling deleteTaskEndpointProjectsProjectIdTasksTaskIdDelete().'
            );
        }

        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling deleteTaskEndpointProjectsProjectIdTasksTaskIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects/{project_id}/tasks/{task_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"task_id"}}`, encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a task from a project accessible to the current user.
     * Delete Task Endpoint
     */
    async deleteTaskEndpointProjectsProjectIdTasksTaskIdDeleteRaw(requestParameters: DeleteTaskEndpointProjectsProjectIdTasksTaskIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteTaskEndpointProjectsProjectIdTasksTaskIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a task from a project accessible to the current user.
     * Delete Task Endpoint
     */
    async deleteTaskEndpointProjectsProjectIdTasksTaskIdDelete(requestParameters: DeleteTaskEndpointProjectsProjectIdTasksTaskIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTaskEndpointProjectsProjectIdTasksTaskIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getActiveProjectSprintCloseConfirmationProjectsProjectIdSprintsActiveCloseConfirmationGet without sending the request
     */
    async getActiveProjectSprintCloseConfirmationProjectsProjectIdSprintsActiveCloseConfirmationGetRequestOpts(requestParameters: GetActiveProjectSprintCloseConfirmationProjectsProjectIdSprintsActiveCloseConfirmationGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getActiveProjectSprintCloseConfirmationProjectsProjectIdSprintsActiveCloseConfirmationGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects/{project_id}/sprints/active/close-confirmation`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Preview the irreversible active sprint close outcome.
     * Get Active Project Sprint Close Confirmation
     */
    async getActiveProjectSprintCloseConfirmationProjectsProjectIdSprintsActiveCloseConfirmationGetRaw(requestParameters: GetActiveProjectSprintCloseConfirmationProjectsProjectIdSprintsActiveCloseConfirmationGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectSprintClosePreviewRead>> {
        const requestOptions = await this.getActiveProjectSprintCloseConfirmationProjectsProjectIdSprintsActiveCloseConfirmationGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectSprintClosePreviewReadFromJSON(jsonValue));
    }

    /**
     * Preview the irreversible active sprint close outcome.
     * Get Active Project Sprint Close Confirmation
     */
    async getActiveProjectSprintCloseConfirmationProjectsProjectIdSprintsActiveCloseConfirmationGet(requestParameters: GetActiveProjectSprintCloseConfirmationProjectsProjectIdSprintsActiveCloseConfirmationGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectSprintClosePreviewRead> {
        const response = await this.getActiveProjectSprintCloseConfirmationProjectsProjectIdSprintsActiveCloseConfirmationGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getActiveProjectSprintProjectsProjectIdSprintsActiveGet without sending the request
     */
    async getActiveProjectSprintProjectsProjectIdSprintsActiveGetRequestOpts(requestParameters: GetActiveProjectSprintProjectsProjectIdSprintsActiveGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getActiveProjectSprintProjectsProjectIdSprintsActiveGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects/{project_id}/sprints/active`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the active sprint for a project accessible to the current user.
     * Get Active Project Sprint
     */
    async getActiveProjectSprintProjectsProjectIdSprintsActiveGetRaw(requestParameters: GetActiveProjectSprintProjectsProjectIdSprintsActiveGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectSprintRead>> {
        const requestOptions = await this.getActiveProjectSprintProjectsProjectIdSprintsActiveGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectSprintReadFromJSON(jsonValue));
    }

    /**
     * Get the active sprint for a project accessible to the current user.
     * Get Active Project Sprint
     */
    async getActiveProjectSprintProjectsProjectIdSprintsActiveGet(requestParameters: GetActiveProjectSprintProjectsProjectIdSprintsActiveGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectSprintRead> {
        const response = await this.getActiveProjectSprintProjectsProjectIdSprintsActiveGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getProjectDoneColumnProjectsProjectIdDoneColumnGet without sending the request
     */
    async getProjectDoneColumnProjectsProjectIdDoneColumnGetRequestOpts(requestParameters: GetProjectDoneColumnProjectsProjectIdDoneColumnGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getProjectDoneColumnProjectsProjectIdDoneColumnGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects/{project_id}/done-column`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the Done Column designation for a project visible to the user.
     * Get Project Done Column
     */
    async getProjectDoneColumnProjectsProjectIdDoneColumnGetRaw(requestParameters: GetProjectDoneColumnProjectsProjectIdDoneColumnGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectDoneColumnRead>> {
        const requestOptions = await this.getProjectDoneColumnProjectsProjectIdDoneColumnGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectDoneColumnReadFromJSON(jsonValue));
    }

    /**
     * Get the Done Column designation for a project visible to the user.
     * Get Project Done Column
     */
    async getProjectDoneColumnProjectsProjectIdDoneColumnGet(requestParameters: GetProjectDoneColumnProjectsProjectIdDoneColumnGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectDoneColumnRead> {
        const response = await this.getProjectDoneColumnProjectsProjectIdDoneColumnGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getProjectProjectsProjectIdGet without sending the request
     */
    async getProjectProjectsProjectIdGetRequestOpts(requestParameters: GetProjectProjectsProjectIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getProjectProjectsProjectIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects/{project_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a project accessible to the current user.
     * Get Project
     */
    async getProjectProjectsProjectIdGetRaw(requestParameters: GetProjectProjectsProjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectRead>> {
        const requestOptions = await this.getProjectProjectsProjectIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectReadFromJSON(jsonValue));
    }

    /**
     * Get a project accessible to the current user.
     * Get Project
     */
    async getProjectProjectsProjectIdGet(requestParameters: GetProjectProjectsProjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectRead> {
        const response = await this.getProjectProjectsProjectIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTaskEndpointProjectsProjectIdTasksTaskIdGet without sending the request
     */
    async getTaskEndpointProjectsProjectIdTasksTaskIdGetRequestOpts(requestParameters: GetTaskEndpointProjectsProjectIdTasksTaskIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getTaskEndpointProjectsProjectIdTasksTaskIdGet().'
            );
        }

        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling getTaskEndpointProjectsProjectIdTasksTaskIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects/{project_id}/tasks/{task_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"task_id"}}`, encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single task from a project accessible to the current user.
     * Get Task Endpoint
     */
    async getTaskEndpointProjectsProjectIdTasksTaskIdGetRaw(requestParameters: GetTaskEndpointProjectsProjectIdTasksTaskIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskRead>> {
        const requestOptions = await this.getTaskEndpointProjectsProjectIdTasksTaskIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskReadFromJSON(jsonValue));
    }

    /**
     * Get a single task from a project accessible to the current user.
     * Get Task Endpoint
     */
    async getTaskEndpointProjectsProjectIdTasksTaskIdGet(requestParameters: GetTaskEndpointProjectsProjectIdTasksTaskIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskRead> {
        const response = await this.getTaskEndpointProjectsProjectIdTasksTaskIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listActiveSprintTasksEndpointProjectsProjectIdTasksActiveSprintGet without sending the request
     */
    async listActiveSprintTasksEndpointProjectsProjectIdTasksActiveSprintGetRequestOpts(requestParameters: ListActiveSprintTasksEndpointProjectsProjectIdTasksActiveSprintGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling listActiveSprintTasksEndpointProjectsProjectIdTasksActiveSprintGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects/{project_id}/tasks/active-sprint`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List tasks selected into the project\'s active sprint.
     * List Active Sprint Tasks Endpoint
     */
    async listActiveSprintTasksEndpointProjectsProjectIdTasksActiveSprintGetRaw(requestParameters: ListActiveSprintTasksEndpointProjectsProjectIdTasksActiveSprintGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TaskRead>>> {
        const requestOptions = await this.listActiveSprintTasksEndpointProjectsProjectIdTasksActiveSprintGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TaskReadFromJSON));
    }

    /**
     * List tasks selected into the project\'s active sprint.
     * List Active Sprint Tasks Endpoint
     */
    async listActiveSprintTasksEndpointProjectsProjectIdTasksActiveSprintGet(requestParameters: ListActiveSprintTasksEndpointProjectsProjectIdTasksActiveSprintGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TaskRead>> {
        const response = await this.listActiveSprintTasksEndpointProjectsProjectIdTasksActiveSprintGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listProjectBacklogProjectsProjectIdBacklogGet without sending the request
     */
    async listProjectBacklogProjectsProjectIdBacklogGetRequestOpts(requestParameters: ListProjectBacklogProjectsProjectIdBacklogGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling listProjectBacklogProjectsProjectIdBacklogGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects/{project_id}/backlog`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List unfinished non-sprint tasks in project Backlog order.
     * List Project Backlog
     */
    async listProjectBacklogProjectsProjectIdBacklogGetRaw(requestParameters: ListProjectBacklogProjectsProjectIdBacklogGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TaskRead>>> {
        const requestOptions = await this.listProjectBacklogProjectsProjectIdBacklogGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TaskReadFromJSON));
    }

    /**
     * List unfinished non-sprint tasks in project Backlog order.
     * List Project Backlog
     */
    async listProjectBacklogProjectsProjectIdBacklogGet(requestParameters: ListProjectBacklogProjectsProjectIdBacklogGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TaskRead>> {
        const response = await this.listProjectBacklogProjectsProjectIdBacklogGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listProjectChatMessagesProjectsProjectIdChatMessagesGet without sending the request
     */
    async listProjectChatMessagesProjectsProjectIdChatMessagesGetRequestOpts(requestParameters: ListProjectChatMessagesProjectsProjectIdChatMessagesGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling listProjectChatMessagesProjectsProjectIdChatMessagesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects/{project_id}/chat/messages`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List chat history for a project accessible to the current user.
     * List Project Chat Messages
     */
    async listProjectChatMessagesProjectsProjectIdChatMessagesGetRaw(requestParameters: ListProjectChatMessagesProjectsProjectIdChatMessagesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProjectChatMessageRead>>> {
        const requestOptions = await this.listProjectChatMessagesProjectsProjectIdChatMessagesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProjectChatMessageReadFromJSON));
    }

    /**
     * List chat history for a project accessible to the current user.
     * List Project Chat Messages
     */
    async listProjectChatMessagesProjectsProjectIdChatMessagesGet(requestParameters: ListProjectChatMessagesProjectsProjectIdChatMessagesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProjectChatMessageRead>> {
        const response = await this.listProjectChatMessagesProjectsProjectIdChatMessagesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listProjectColumnsProjectsProjectIdColumnsGet without sending the request
     */
    async listProjectColumnsProjectsProjectIdColumnsGetRequestOpts(requestParameters: ListProjectColumnsProjectsProjectIdColumnsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling listProjectColumnsProjectsProjectIdColumnsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects/{project_id}/columns`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List workflow columns for a project accessible to the current user.
     * List Project Columns
     */
    async listProjectColumnsProjectsProjectIdColumnsGetRaw(requestParameters: ListProjectColumnsProjectsProjectIdColumnsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProjectColumnRead>>> {
        const requestOptions = await this.listProjectColumnsProjectsProjectIdColumnsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProjectColumnReadFromJSON));
    }

    /**
     * List workflow columns for a project accessible to the current user.
     * List Project Columns
     */
    async listProjectColumnsProjectsProjectIdColumnsGet(requestParameters: ListProjectColumnsProjectsProjectIdColumnsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProjectColumnRead>> {
        const response = await this.listProjectColumnsProjectsProjectIdColumnsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listProjectSprintHistoryProjectsProjectIdSprintsHistoryGet without sending the request
     */
    async listProjectSprintHistoryProjectsProjectIdSprintsHistoryGetRequestOpts(requestParameters: ListProjectSprintHistoryProjectsProjectIdSprintsHistoryGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling listProjectSprintHistoryProjectsProjectIdSprintsHistoryGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects/{project_id}/sprints/history`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List closed sprint history for a project participant.
     * List Project Sprint History
     */
    async listProjectSprintHistoryProjectsProjectIdSprintsHistoryGetRaw(requestParameters: ListProjectSprintHistoryProjectsProjectIdSprintsHistoryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProjectSprintHistoryRead>>> {
        const requestOptions = await this.listProjectSprintHistoryProjectsProjectIdSprintsHistoryGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProjectSprintHistoryReadFromJSON));
    }

    /**
     * List closed sprint history for a project participant.
     * List Project Sprint History
     */
    async listProjectSprintHistoryProjectsProjectIdSprintsHistoryGet(requestParameters: ListProjectSprintHistoryProjectsProjectIdSprintsHistoryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProjectSprintHistoryRead>> {
        const response = await this.listProjectSprintHistoryProjectsProjectIdSprintsHistoryGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listProjectsProjectsGet without sending the request
     */
    async listProjectsProjectsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List projects accessible to the current user.
     * List Projects
     */
    async listProjectsProjectsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProjectRead>>> {
        const requestOptions = await this.listProjectsProjectsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProjectReadFromJSON));
    }

    /**
     * List projects accessible to the current user.
     * List Projects
     */
    async listProjectsProjectsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProjectRead>> {
        const response = await this.listProjectsProjectsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listTasksEndpointProjectsProjectIdTasksGet without sending the request
     */
    async listTasksEndpointProjectsProjectIdTasksGetRequestOpts(requestParameters: ListTasksEndpointProjectsProjectIdTasksGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling listTasksEndpointProjectsProjectIdTasksGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects/{project_id}/tasks`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List tasks for a project accessible to the current user.
     * List Tasks Endpoint
     */
    async listTasksEndpointProjectsProjectIdTasksGetRaw(requestParameters: ListTasksEndpointProjectsProjectIdTasksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TaskRead>>> {
        const requestOptions = await this.listTasksEndpointProjectsProjectIdTasksGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TaskReadFromJSON));
    }

    /**
     * List tasks for a project accessible to the current user.
     * List Tasks Endpoint
     */
    async listTasksEndpointProjectsProjectIdTasksGet(requestParameters: ListTasksEndpointProjectsProjectIdTasksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TaskRead>> {
        const response = await this.listTasksEndpointProjectsProjectIdTasksGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for moveTaskEndpointProjectsProjectIdTasksTaskIdMovePut without sending the request
     */
    async moveTaskEndpointProjectsProjectIdTasksTaskIdMovePutRequestOpts(requestParameters: MoveTaskEndpointProjectsProjectIdTasksTaskIdMovePutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling moveTaskEndpointProjectsProjectIdTasksTaskIdMovePut().'
            );
        }

        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling moveTaskEndpointProjectsProjectIdTasksTaskIdMovePut().'
            );
        }

        if (requestParameters['taskDestination'] == null) {
            throw new runtime.RequiredError(
                'taskDestination',
                'Required parameter "taskDestination" was null or undefined when calling moveTaskEndpointProjectsProjectIdTasksTaskIdMovePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/projects/{project_id}/tasks/{task_id}/move`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"task_id"}}`, encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TaskDestinationToJSON(requestParameters['taskDestination']),
        };
    }

    /**
     * Move a task to a board destination accessible to the current user.
     * Move Task Endpoint
     */
    async moveTaskEndpointProjectsProjectIdTasksTaskIdMovePutRaw(requestParameters: MoveTaskEndpointProjectsProjectIdTasksTaskIdMovePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskRead>> {
        const requestOptions = await this.moveTaskEndpointProjectsProjectIdTasksTaskIdMovePutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskReadFromJSON(jsonValue));
    }

    /**
     * Move a task to a board destination accessible to the current user.
     * Move Task Endpoint
     */
    async moveTaskEndpointProjectsProjectIdTasksTaskIdMovePut(requestParameters: MoveTaskEndpointProjectsProjectIdTasksTaskIdMovePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskRead> {
        const response = await this.moveTaskEndpointProjectsProjectIdTasksTaskIdMovePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for removeTaskFromActiveProjectSprintProjectsProjectIdSprintsActiveTasksTaskIdDelete without sending the request
     */
    async removeTaskFromActiveProjectSprintProjectsProjectIdSprintsActiveTasksTaskIdDeleteRequestOpts(requestParameters: RemoveTaskFromActiveProjectSprintProjectsProjectIdSprintsActiveTasksTaskIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling removeTaskFromActiveProjectSprintProjectsProjectIdSprintsActiveTasksTaskIdDelete().'
            );
        }

        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling removeTaskFromActiveProjectSprintProjectsProjectIdSprintsActiveTasksTaskIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects/{project_id}/sprints/active/tasks/{task_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"task_id"}}`, encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove an active sprint task back to the project Backlog.
     * Remove Task From Active Project Sprint
     */
    async removeTaskFromActiveProjectSprintProjectsProjectIdSprintsActiveTasksTaskIdDeleteRaw(requestParameters: RemoveTaskFromActiveProjectSprintProjectsProjectIdSprintsActiveTasksTaskIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskRead>> {
        const requestOptions = await this.removeTaskFromActiveProjectSprintProjectsProjectIdSprintsActiveTasksTaskIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskReadFromJSON(jsonValue));
    }

    /**
     * Remove an active sprint task back to the project Backlog.
     * Remove Task From Active Project Sprint
     */
    async removeTaskFromActiveProjectSprintProjectsProjectIdSprintsActiveTasksTaskIdDelete(requestParameters: RemoveTaskFromActiveProjectSprintProjectsProjectIdSprintsActiveTasksTaskIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskRead> {
        const response = await this.removeTaskFromActiveProjectSprintProjectsProjectIdSprintsActiveTasksTaskIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for reorderProjectBacklogProjectsProjectIdBacklogReorderPut without sending the request
     */
    async reorderProjectBacklogProjectsProjectIdBacklogReorderPutRequestOpts(requestParameters: ReorderProjectBacklogProjectsProjectIdBacklogReorderPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling reorderProjectBacklogProjectsProjectIdBacklogReorderPut().'
            );
        }

        if (requestParameters['projectBacklogReorder'] == null) {
            throw new runtime.RequiredError(
                'projectBacklogReorder',
                'Required parameter "projectBacklogReorder" was null or undefined when calling reorderProjectBacklogProjectsProjectIdBacklogReorderPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/projects/{project_id}/backlog/reorder`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectBacklogReorderToJSON(requestParameters['projectBacklogReorder']),
        };
    }

    /**
     * Persist a complete manual Backlog task order.
     * Reorder Project Backlog
     */
    async reorderProjectBacklogProjectsProjectIdBacklogReorderPutRaw(requestParameters: ReorderProjectBacklogProjectsProjectIdBacklogReorderPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TaskRead>>> {
        const requestOptions = await this.reorderProjectBacklogProjectsProjectIdBacklogReorderPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TaskReadFromJSON));
    }

    /**
     * Persist a complete manual Backlog task order.
     * Reorder Project Backlog
     */
    async reorderProjectBacklogProjectsProjectIdBacklogReorderPut(requestParameters: ReorderProjectBacklogProjectsProjectIdBacklogReorderPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TaskRead>> {
        const response = await this.reorderProjectBacklogProjectsProjectIdBacklogReorderPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for reorderProjectColumnsProjectsProjectIdColumnsReorderPut without sending the request
     */
    async reorderProjectColumnsProjectsProjectIdColumnsReorderPutRequestOpts(requestParameters: ReorderProjectColumnsProjectsProjectIdColumnsReorderPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling reorderProjectColumnsProjectsProjectIdColumnsReorderPut().'
            );
        }

        if (requestParameters['projectColumnReorder'] == null) {
            throw new runtime.RequiredError(
                'projectColumnReorder',
                'Required parameter "projectColumnReorder" was null or undefined when calling reorderProjectColumnsProjectsProjectIdColumnsReorderPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/projects/{project_id}/columns/reorder`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectColumnReorderToJSON(requestParameters['projectColumnReorder']),
        };
    }

    /**
     * Reorder all workflow columns for a project owned by the current user.
     * Reorder Project Columns
     */
    async reorderProjectColumnsProjectsProjectIdColumnsReorderPutRaw(requestParameters: ReorderProjectColumnsProjectsProjectIdColumnsReorderPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProjectColumnRead>>> {
        const requestOptions = await this.reorderProjectColumnsProjectsProjectIdColumnsReorderPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProjectColumnReadFromJSON));
    }

    /**
     * Reorder all workflow columns for a project owned by the current user.
     * Reorder Project Columns
     */
    async reorderProjectColumnsProjectsProjectIdColumnsReorderPut(requestParameters: ReorderProjectColumnsProjectsProjectIdColumnsReorderPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProjectColumnRead>> {
        const response = await this.reorderProjectColumnsProjectsProjectIdColumnsReorderPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateActiveProjectSprintProjectsProjectIdSprintsActivePatch without sending the request
     */
    async updateActiveProjectSprintProjectsProjectIdSprintsActivePatchRequestOpts(requestParameters: UpdateActiveProjectSprintProjectsProjectIdSprintsActivePatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling updateActiveProjectSprintProjectsProjectIdSprintsActivePatch().'
            );
        }

        if (requestParameters['projectSprintUpdate'] == null) {
            throw new runtime.RequiredError(
                'projectSprintUpdate',
                'Required parameter "projectSprintUpdate" was null or undefined when calling updateActiveProjectSprintProjectsProjectIdSprintsActivePatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/projects/{project_id}/sprints/active`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectSprintUpdateToJSON(requestParameters['projectSprintUpdate']),
        };
    }

    /**
     * Update active sprint metadata for a project owned by the current user.
     * Update Active Project Sprint
     */
    async updateActiveProjectSprintProjectsProjectIdSprintsActivePatchRaw(requestParameters: UpdateActiveProjectSprintProjectsProjectIdSprintsActivePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectSprintRead>> {
        const requestOptions = await this.updateActiveProjectSprintProjectsProjectIdSprintsActivePatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectSprintReadFromJSON(jsonValue));
    }

    /**
     * Update active sprint metadata for a project owned by the current user.
     * Update Active Project Sprint
     */
    async updateActiveProjectSprintProjectsProjectIdSprintsActivePatch(requestParameters: UpdateActiveProjectSprintProjectsProjectIdSprintsActivePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectSprintRead> {
        const response = await this.updateActiveProjectSprintProjectsProjectIdSprintsActivePatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateProjectColumnProjectsProjectIdColumnsColumnIdPatch without sending the request
     */
    async updateProjectColumnProjectsProjectIdColumnsColumnIdPatchRequestOpts(requestParameters: UpdateProjectColumnProjectsProjectIdColumnsColumnIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling updateProjectColumnProjectsProjectIdColumnsColumnIdPatch().'
            );
        }

        if (requestParameters['columnId'] == null) {
            throw new runtime.RequiredError(
                'columnId',
                'Required parameter "columnId" was null or undefined when calling updateProjectColumnProjectsProjectIdColumnsColumnIdPatch().'
            );
        }

        if (requestParameters['projectColumnUpdate'] == null) {
            throw new runtime.RequiredError(
                'projectColumnUpdate',
                'Required parameter "projectColumnUpdate" was null or undefined when calling updateProjectColumnProjectsProjectIdColumnsColumnIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/projects/{project_id}/columns/{column_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"column_id"}}`, encodeURIComponent(String(requestParameters['columnId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectColumnUpdateToJSON(requestParameters['projectColumnUpdate']),
        };
    }

    /**
     * Rename a workflow column for a project owned by the current user.
     * Update Project Column
     */
    async updateProjectColumnProjectsProjectIdColumnsColumnIdPatchRaw(requestParameters: UpdateProjectColumnProjectsProjectIdColumnsColumnIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectColumnRead>> {
        const requestOptions = await this.updateProjectColumnProjectsProjectIdColumnsColumnIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectColumnReadFromJSON(jsonValue));
    }

    /**
     * Rename a workflow column for a project owned by the current user.
     * Update Project Column
     */
    async updateProjectColumnProjectsProjectIdColumnsColumnIdPatch(requestParameters: UpdateProjectColumnProjectsProjectIdColumnsColumnIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectColumnRead> {
        const response = await this.updateProjectColumnProjectsProjectIdColumnsColumnIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateProjectDoneColumnProjectsProjectIdDoneColumnPatch without sending the request
     */
    async updateProjectDoneColumnProjectsProjectIdDoneColumnPatchRequestOpts(requestParameters: UpdateProjectDoneColumnProjectsProjectIdDoneColumnPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling updateProjectDoneColumnProjectsProjectIdDoneColumnPatch().'
            );
        }

        if (requestParameters['projectDoneColumnUpdate'] == null) {
            throw new runtime.RequiredError(
                'projectDoneColumnUpdate',
                'Required parameter "projectDoneColumnUpdate" was null or undefined when calling updateProjectDoneColumnProjectsProjectIdDoneColumnPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/projects/{project_id}/done-column`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectDoneColumnUpdateToJSON(requestParameters['projectDoneColumnUpdate']),
        };
    }

    /**
     * Change the Done Column designation for a project owned by the user.
     * Update Project Done Column
     */
    async updateProjectDoneColumnProjectsProjectIdDoneColumnPatchRaw(requestParameters: UpdateProjectDoneColumnProjectsProjectIdDoneColumnPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectDoneColumnRead>> {
        const requestOptions = await this.updateProjectDoneColumnProjectsProjectIdDoneColumnPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectDoneColumnReadFromJSON(jsonValue));
    }

    /**
     * Change the Done Column designation for a project owned by the user.
     * Update Project Done Column
     */
    async updateProjectDoneColumnProjectsProjectIdDoneColumnPatch(requestParameters: UpdateProjectDoneColumnProjectsProjectIdDoneColumnPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectDoneColumnRead> {
        const response = await this.updateProjectDoneColumnProjectsProjectIdDoneColumnPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateProjectProjectsProjectIdPatch without sending the request
     */
    async updateProjectProjectsProjectIdPatchRequestOpts(requestParameters: UpdateProjectProjectsProjectIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling updateProjectProjectsProjectIdPatch().'
            );
        }

        if (requestParameters['projectUpdate'] == null) {
            throw new runtime.RequiredError(
                'projectUpdate',
                'Required parameter "projectUpdate" was null or undefined when calling updateProjectProjectsProjectIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/projects/{project_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectUpdateToJSON(requestParameters['projectUpdate']),
        };
    }

    /**
     * Update a project owned by the current user.
     * Update Project
     */
    async updateProjectProjectsProjectIdPatchRaw(requestParameters: UpdateProjectProjectsProjectIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectRead>> {
        const requestOptions = await this.updateProjectProjectsProjectIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectReadFromJSON(jsonValue));
    }

    /**
     * Update a project owned by the current user.
     * Update Project
     */
    async updateProjectProjectsProjectIdPatch(requestParameters: UpdateProjectProjectsProjectIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectRead> {
        const response = await this.updateProjectProjectsProjectIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateTaskEndpointProjectsProjectIdTasksTaskIdPatch without sending the request
     */
    async updateTaskEndpointProjectsProjectIdTasksTaskIdPatchRequestOpts(requestParameters: UpdateTaskEndpointProjectsProjectIdTasksTaskIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling updateTaskEndpointProjectsProjectIdTasksTaskIdPatch().'
            );
        }

        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling updateTaskEndpointProjectsProjectIdTasksTaskIdPatch().'
            );
        }

        if (requestParameters['taskUpdate'] == null) {
            throw new runtime.RequiredError(
                'taskUpdate',
                'Required parameter "taskUpdate" was null or undefined when calling updateTaskEndpointProjectsProjectIdTasksTaskIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/projects/{project_id}/tasks/{task_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"task_id"}}`, encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TaskUpdateToJSON(requestParameters['taskUpdate']),
        };
    }

    /**
     * Update a task in a project accessible to the current user.
     * Update Task Endpoint
     */
    async updateTaskEndpointProjectsProjectIdTasksTaskIdPatchRaw(requestParameters: UpdateTaskEndpointProjectsProjectIdTasksTaskIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskRead>> {
        const requestOptions = await this.updateTaskEndpointProjectsProjectIdTasksTaskIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskReadFromJSON(jsonValue));
    }

    /**
     * Update a task in a project accessible to the current user.
     * Update Task Endpoint
     */
    async updateTaskEndpointProjectsProjectIdTasksTaskIdPatch(requestParameters: UpdateTaskEndpointProjectsProjectIdTasksTaskIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskRead> {
        const response = await this.updateTaskEndpointProjectsProjectIdTasksTaskIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
