// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  ProjectColumnCreate,
  ProjectColumnRead,
  ProjectColumnReorder,
  ProjectColumnUpdate,
  ProjectCreate,
  ProjectMemberCreate,
  ProjectRead,
  ProjectUpdate,
  TaskCreate,
  TaskDestination,
  TaskRead,
  TaskUpdate,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ProjectColumnCreateFromJSON,
    ProjectColumnCreateToJSON,
    ProjectColumnReadFromJSON,
    ProjectColumnReadToJSON,
    ProjectColumnReorderFromJSON,
    ProjectColumnReorderToJSON,
    ProjectColumnUpdateFromJSON,
    ProjectColumnUpdateToJSON,
    ProjectCreateFromJSON,
    ProjectCreateToJSON,
    ProjectMemberCreateFromJSON,
    ProjectMemberCreateToJSON,
    ProjectReadFromJSON,
    ProjectReadToJSON,
    ProjectUpdateFromJSON,
    ProjectUpdateToJSON,
    TaskCreateFromJSON,
    TaskCreateToJSON,
    TaskDestinationFromJSON,
    TaskDestinationToJSON,
    TaskReadFromJSON,
    TaskReadToJSON,
    TaskUpdateFromJSON,
    TaskUpdateToJSON,
} from '../models/index';

export interface AddProjectMemberProjectsProjectIdMembersPostRequest {
    projectId: string;
    projectMemberCreate: ProjectMemberCreate;
}

export interface CreateProjectColumnProjectsProjectIdColumnsPostRequest {
    projectId: string;
    projectColumnCreate: ProjectColumnCreate;
}

export interface CreateProjectEndpointProjectsPostRequest {
    projectCreate: ProjectCreate;
}

export interface CreateTaskEndpointProjectsProjectIdTasksPostRequest {
    projectId: string;
    taskCreate: TaskCreate;
}

export interface DeleteProjectColumnProjectsProjectIdColumnsColumnIdDeleteRequest {
    projectId: string;
    columnId: string;
}

export interface DeleteProjectProjectsProjectIdDeleteRequest {
    projectId: string;
}

export interface DeleteTaskEndpointProjectsProjectIdTasksTaskIdDeleteRequest {
    projectId: string;
    taskId: string;
}

export interface GetProjectProjectsProjectIdGetRequest {
    projectId: string;
}

export interface GetTaskEndpointProjectsProjectIdTasksTaskIdGetRequest {
    projectId: string;
    taskId: string;
}

export interface ListProjectColumnsProjectsProjectIdColumnsGetRequest {
    projectId: string;
}

export interface ListTasksEndpointProjectsProjectIdTasksGetRequest {
    projectId: string;
}

export interface MoveTaskEndpointProjectsProjectIdTasksTaskIdMovePutRequest {
    projectId: string;
    taskId: string;
    taskDestination: TaskDestination;
}

export interface ReorderProjectColumnsProjectsProjectIdColumnsReorderPutRequest {
    projectId: string;
    projectColumnReorder: ProjectColumnReorder;
}

export interface UpdateProjectColumnProjectsProjectIdColumnsColumnIdPatchRequest {
    projectId: string;
    columnId: string;
    projectColumnUpdate: ProjectColumnUpdate;
}

export interface UpdateProjectProjectsProjectIdPatchRequest {
    projectId: string;
    projectUpdate: ProjectUpdate;
}

export interface UpdateTaskEndpointProjectsProjectIdTasksTaskIdPatchRequest {
    projectId: string;
    taskId: string;
    taskUpdate: TaskUpdate;
}

/**
 * 
 */
export class ProjectsApi extends runtime.BaseAPI {

    /**
     * Creates request options for addProjectMemberProjectsProjectIdMembersPost without sending the request
     */
    async addProjectMemberProjectsProjectIdMembersPostRequestOpts(requestParameters: AddProjectMemberProjectsProjectIdMembersPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling addProjectMemberProjectsProjectIdMembersPost().'
            );
        }

        if (requestParameters['projectMemberCreate'] == null) {
            throw new runtime.RequiredError(
                'projectMemberCreate',
                'Required parameter "projectMemberCreate" was null or undefined when calling addProjectMemberProjectsProjectIdMembersPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/projects/{project_id}/members`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectMemberCreateToJSON(requestParameters['projectMemberCreate']),
        };
    }

    /**
     * Add a member to a project owned by the current user.
     * Add Project Member
     */
    async addProjectMemberProjectsProjectIdMembersPostRaw(requestParameters: AddProjectMemberProjectsProjectIdMembersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectRead>> {
        const requestOptions = await this.addProjectMemberProjectsProjectIdMembersPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectReadFromJSON(jsonValue));
    }

    /**
     * Add a member to a project owned by the current user.
     * Add Project Member
     */
    async addProjectMemberProjectsProjectIdMembersPost(requestParameters: AddProjectMemberProjectsProjectIdMembersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectRead> {
        const response = await this.addProjectMemberProjectsProjectIdMembersPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createProjectColumnProjectsProjectIdColumnsPost without sending the request
     */
    async createProjectColumnProjectsProjectIdColumnsPostRequestOpts(requestParameters: CreateProjectColumnProjectsProjectIdColumnsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling createProjectColumnProjectsProjectIdColumnsPost().'
            );
        }

        if (requestParameters['projectColumnCreate'] == null) {
            throw new runtime.RequiredError(
                'projectColumnCreate',
                'Required parameter "projectColumnCreate" was null or undefined when calling createProjectColumnProjectsProjectIdColumnsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/projects/{project_id}/columns`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectColumnCreateToJSON(requestParameters['projectColumnCreate']),
        };
    }

    /**
     * Create a workflow column for a project owned by the current user.
     * Create Project Column
     */
    async createProjectColumnProjectsProjectIdColumnsPostRaw(requestParameters: CreateProjectColumnProjectsProjectIdColumnsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectColumnRead>> {
        const requestOptions = await this.createProjectColumnProjectsProjectIdColumnsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectColumnReadFromJSON(jsonValue));
    }

    /**
     * Create a workflow column for a project owned by the current user.
     * Create Project Column
     */
    async createProjectColumnProjectsProjectIdColumnsPost(requestParameters: CreateProjectColumnProjectsProjectIdColumnsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectColumnRead> {
        const response = await this.createProjectColumnProjectsProjectIdColumnsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createProjectEndpointProjectsPost without sending the request
     */
    async createProjectEndpointProjectsPostRequestOpts(requestParameters: CreateProjectEndpointProjectsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectCreate'] == null) {
            throw new runtime.RequiredError(
                'projectCreate',
                'Required parameter "projectCreate" was null or undefined when calling createProjectEndpointProjectsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/projects`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectCreateToJSON(requestParameters['projectCreate']),
        };
    }

    /**
     * Create a project for the current user.
     * Create Project Endpoint
     */
    async createProjectEndpointProjectsPostRaw(requestParameters: CreateProjectEndpointProjectsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectRead>> {
        const requestOptions = await this.createProjectEndpointProjectsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectReadFromJSON(jsonValue));
    }

    /**
     * Create a project for the current user.
     * Create Project Endpoint
     */
    async createProjectEndpointProjectsPost(requestParameters: CreateProjectEndpointProjectsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectRead> {
        const response = await this.createProjectEndpointProjectsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createTaskEndpointProjectsProjectIdTasksPost without sending the request
     */
    async createTaskEndpointProjectsProjectIdTasksPostRequestOpts(requestParameters: CreateTaskEndpointProjectsProjectIdTasksPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling createTaskEndpointProjectsProjectIdTasksPost().'
            );
        }

        if (requestParameters['taskCreate'] == null) {
            throw new runtime.RequiredError(
                'taskCreate',
                'Required parameter "taskCreate" was null or undefined when calling createTaskEndpointProjectsProjectIdTasksPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/projects/{project_id}/tasks`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TaskCreateToJSON(requestParameters['taskCreate']),
        };
    }

    /**
     * Create a task in a project accessible to the current user.
     * Create Task Endpoint
     */
    async createTaskEndpointProjectsProjectIdTasksPostRaw(requestParameters: CreateTaskEndpointProjectsProjectIdTasksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskRead>> {
        const requestOptions = await this.createTaskEndpointProjectsProjectIdTasksPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskReadFromJSON(jsonValue));
    }

    /**
     * Create a task in a project accessible to the current user.
     * Create Task Endpoint
     */
    async createTaskEndpointProjectsProjectIdTasksPost(requestParameters: CreateTaskEndpointProjectsProjectIdTasksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskRead> {
        const response = await this.createTaskEndpointProjectsProjectIdTasksPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteProjectColumnProjectsProjectIdColumnsColumnIdDelete without sending the request
     */
    async deleteProjectColumnProjectsProjectIdColumnsColumnIdDeleteRequestOpts(requestParameters: DeleteProjectColumnProjectsProjectIdColumnsColumnIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling deleteProjectColumnProjectsProjectIdColumnsColumnIdDelete().'
            );
        }

        if (requestParameters['columnId'] == null) {
            throw new runtime.RequiredError(
                'columnId',
                'Required parameter "columnId" was null or undefined when calling deleteProjectColumnProjectsProjectIdColumnsColumnIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects/{project_id}/columns/{column_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"column_id"}}`, encodeURIComponent(String(requestParameters['columnId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete an empty workflow column from a project owned by the current user.
     * Delete Project Column
     */
    async deleteProjectColumnProjectsProjectIdColumnsColumnIdDeleteRaw(requestParameters: DeleteProjectColumnProjectsProjectIdColumnsColumnIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteProjectColumnProjectsProjectIdColumnsColumnIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an empty workflow column from a project owned by the current user.
     * Delete Project Column
     */
    async deleteProjectColumnProjectsProjectIdColumnsColumnIdDelete(requestParameters: DeleteProjectColumnProjectsProjectIdColumnsColumnIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteProjectColumnProjectsProjectIdColumnsColumnIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteProjectProjectsProjectIdDelete without sending the request
     */
    async deleteProjectProjectsProjectIdDeleteRequestOpts(requestParameters: DeleteProjectProjectsProjectIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling deleteProjectProjectsProjectIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects/{project_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a project owned by the current user.
     * Delete Project
     */
    async deleteProjectProjectsProjectIdDeleteRaw(requestParameters: DeleteProjectProjectsProjectIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteProjectProjectsProjectIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a project owned by the current user.
     * Delete Project
     */
    async deleteProjectProjectsProjectIdDelete(requestParameters: DeleteProjectProjectsProjectIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteProjectProjectsProjectIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteTaskEndpointProjectsProjectIdTasksTaskIdDelete without sending the request
     */
    async deleteTaskEndpointProjectsProjectIdTasksTaskIdDeleteRequestOpts(requestParameters: DeleteTaskEndpointProjectsProjectIdTasksTaskIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling deleteTaskEndpointProjectsProjectIdTasksTaskIdDelete().'
            );
        }

        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling deleteTaskEndpointProjectsProjectIdTasksTaskIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects/{project_id}/tasks/{task_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"task_id"}}`, encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a task from a project accessible to the current user.
     * Delete Task Endpoint
     */
    async deleteTaskEndpointProjectsProjectIdTasksTaskIdDeleteRaw(requestParameters: DeleteTaskEndpointProjectsProjectIdTasksTaskIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteTaskEndpointProjectsProjectIdTasksTaskIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a task from a project accessible to the current user.
     * Delete Task Endpoint
     */
    async deleteTaskEndpointProjectsProjectIdTasksTaskIdDelete(requestParameters: DeleteTaskEndpointProjectsProjectIdTasksTaskIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTaskEndpointProjectsProjectIdTasksTaskIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getProjectProjectsProjectIdGet without sending the request
     */
    async getProjectProjectsProjectIdGetRequestOpts(requestParameters: GetProjectProjectsProjectIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getProjectProjectsProjectIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects/{project_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a project accessible to the current user.
     * Get Project
     */
    async getProjectProjectsProjectIdGetRaw(requestParameters: GetProjectProjectsProjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectRead>> {
        const requestOptions = await this.getProjectProjectsProjectIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectReadFromJSON(jsonValue));
    }

    /**
     * Get a project accessible to the current user.
     * Get Project
     */
    async getProjectProjectsProjectIdGet(requestParameters: GetProjectProjectsProjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectRead> {
        const response = await this.getProjectProjectsProjectIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTaskEndpointProjectsProjectIdTasksTaskIdGet without sending the request
     */
    async getTaskEndpointProjectsProjectIdTasksTaskIdGetRequestOpts(requestParameters: GetTaskEndpointProjectsProjectIdTasksTaskIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getTaskEndpointProjectsProjectIdTasksTaskIdGet().'
            );
        }

        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling getTaskEndpointProjectsProjectIdTasksTaskIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects/{project_id}/tasks/{task_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"task_id"}}`, encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single task from a project accessible to the current user.
     * Get Task Endpoint
     */
    async getTaskEndpointProjectsProjectIdTasksTaskIdGetRaw(requestParameters: GetTaskEndpointProjectsProjectIdTasksTaskIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskRead>> {
        const requestOptions = await this.getTaskEndpointProjectsProjectIdTasksTaskIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskReadFromJSON(jsonValue));
    }

    /**
     * Get a single task from a project accessible to the current user.
     * Get Task Endpoint
     */
    async getTaskEndpointProjectsProjectIdTasksTaskIdGet(requestParameters: GetTaskEndpointProjectsProjectIdTasksTaskIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskRead> {
        const response = await this.getTaskEndpointProjectsProjectIdTasksTaskIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listProjectColumnsProjectsProjectIdColumnsGet without sending the request
     */
    async listProjectColumnsProjectsProjectIdColumnsGetRequestOpts(requestParameters: ListProjectColumnsProjectsProjectIdColumnsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling listProjectColumnsProjectsProjectIdColumnsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects/{project_id}/columns`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List workflow columns for a project accessible to the current user.
     * List Project Columns
     */
    async listProjectColumnsProjectsProjectIdColumnsGetRaw(requestParameters: ListProjectColumnsProjectsProjectIdColumnsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProjectColumnRead>>> {
        const requestOptions = await this.listProjectColumnsProjectsProjectIdColumnsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProjectColumnReadFromJSON));
    }

    /**
     * List workflow columns for a project accessible to the current user.
     * List Project Columns
     */
    async listProjectColumnsProjectsProjectIdColumnsGet(requestParameters: ListProjectColumnsProjectsProjectIdColumnsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProjectColumnRead>> {
        const response = await this.listProjectColumnsProjectsProjectIdColumnsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listProjectsProjectsGet without sending the request
     */
    async listProjectsProjectsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List projects accessible to the current user.
     * List Projects
     */
    async listProjectsProjectsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProjectRead>>> {
        const requestOptions = await this.listProjectsProjectsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProjectReadFromJSON));
    }

    /**
     * List projects accessible to the current user.
     * List Projects
     */
    async listProjectsProjectsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProjectRead>> {
        const response = await this.listProjectsProjectsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listTasksEndpointProjectsProjectIdTasksGet without sending the request
     */
    async listTasksEndpointProjectsProjectIdTasksGetRequestOpts(requestParameters: ListTasksEndpointProjectsProjectIdTasksGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling listTasksEndpointProjectsProjectIdTasksGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects/{project_id}/tasks`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List tasks for a project accessible to the current user.
     * List Tasks Endpoint
     */
    async listTasksEndpointProjectsProjectIdTasksGetRaw(requestParameters: ListTasksEndpointProjectsProjectIdTasksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TaskRead>>> {
        const requestOptions = await this.listTasksEndpointProjectsProjectIdTasksGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TaskReadFromJSON));
    }

    /**
     * List tasks for a project accessible to the current user.
     * List Tasks Endpoint
     */
    async listTasksEndpointProjectsProjectIdTasksGet(requestParameters: ListTasksEndpointProjectsProjectIdTasksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TaskRead>> {
        const response = await this.listTasksEndpointProjectsProjectIdTasksGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for moveTaskEndpointProjectsProjectIdTasksTaskIdMovePut without sending the request
     */
    async moveTaskEndpointProjectsProjectIdTasksTaskIdMovePutRequestOpts(requestParameters: MoveTaskEndpointProjectsProjectIdTasksTaskIdMovePutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling moveTaskEndpointProjectsProjectIdTasksTaskIdMovePut().'
            );
        }

        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling moveTaskEndpointProjectsProjectIdTasksTaskIdMovePut().'
            );
        }

        if (requestParameters['taskDestination'] == null) {
            throw new runtime.RequiredError(
                'taskDestination',
                'Required parameter "taskDestination" was null or undefined when calling moveTaskEndpointProjectsProjectIdTasksTaskIdMovePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/projects/{project_id}/tasks/{task_id}/move`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"task_id"}}`, encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TaskDestinationToJSON(requestParameters['taskDestination']),
        };
    }

    /**
     * Move a task to a board destination accessible to the current user.
     * Move Task Endpoint
     */
    async moveTaskEndpointProjectsProjectIdTasksTaskIdMovePutRaw(requestParameters: MoveTaskEndpointProjectsProjectIdTasksTaskIdMovePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskRead>> {
        const requestOptions = await this.moveTaskEndpointProjectsProjectIdTasksTaskIdMovePutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskReadFromJSON(jsonValue));
    }

    /**
     * Move a task to a board destination accessible to the current user.
     * Move Task Endpoint
     */
    async moveTaskEndpointProjectsProjectIdTasksTaskIdMovePut(requestParameters: MoveTaskEndpointProjectsProjectIdTasksTaskIdMovePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskRead> {
        const response = await this.moveTaskEndpointProjectsProjectIdTasksTaskIdMovePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for reorderProjectColumnsProjectsProjectIdColumnsReorderPut without sending the request
     */
    async reorderProjectColumnsProjectsProjectIdColumnsReorderPutRequestOpts(requestParameters: ReorderProjectColumnsProjectsProjectIdColumnsReorderPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling reorderProjectColumnsProjectsProjectIdColumnsReorderPut().'
            );
        }

        if (requestParameters['projectColumnReorder'] == null) {
            throw new runtime.RequiredError(
                'projectColumnReorder',
                'Required parameter "projectColumnReorder" was null or undefined when calling reorderProjectColumnsProjectsProjectIdColumnsReorderPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/projects/{project_id}/columns/reorder`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectColumnReorderToJSON(requestParameters['projectColumnReorder']),
        };
    }

    /**
     * Reorder all workflow columns for a project owned by the current user.
     * Reorder Project Columns
     */
    async reorderProjectColumnsProjectsProjectIdColumnsReorderPutRaw(requestParameters: ReorderProjectColumnsProjectsProjectIdColumnsReorderPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProjectColumnRead>>> {
        const requestOptions = await this.reorderProjectColumnsProjectsProjectIdColumnsReorderPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProjectColumnReadFromJSON));
    }

    /**
     * Reorder all workflow columns for a project owned by the current user.
     * Reorder Project Columns
     */
    async reorderProjectColumnsProjectsProjectIdColumnsReorderPut(requestParameters: ReorderProjectColumnsProjectsProjectIdColumnsReorderPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProjectColumnRead>> {
        const response = await this.reorderProjectColumnsProjectsProjectIdColumnsReorderPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateProjectColumnProjectsProjectIdColumnsColumnIdPatch without sending the request
     */
    async updateProjectColumnProjectsProjectIdColumnsColumnIdPatchRequestOpts(requestParameters: UpdateProjectColumnProjectsProjectIdColumnsColumnIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling updateProjectColumnProjectsProjectIdColumnsColumnIdPatch().'
            );
        }

        if (requestParameters['columnId'] == null) {
            throw new runtime.RequiredError(
                'columnId',
                'Required parameter "columnId" was null or undefined when calling updateProjectColumnProjectsProjectIdColumnsColumnIdPatch().'
            );
        }

        if (requestParameters['projectColumnUpdate'] == null) {
            throw new runtime.RequiredError(
                'projectColumnUpdate',
                'Required parameter "projectColumnUpdate" was null or undefined when calling updateProjectColumnProjectsProjectIdColumnsColumnIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/projects/{project_id}/columns/{column_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"column_id"}}`, encodeURIComponent(String(requestParameters['columnId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectColumnUpdateToJSON(requestParameters['projectColumnUpdate']),
        };
    }

    /**
     * Rename a workflow column for a project owned by the current user.
     * Update Project Column
     */
    async updateProjectColumnProjectsProjectIdColumnsColumnIdPatchRaw(requestParameters: UpdateProjectColumnProjectsProjectIdColumnsColumnIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectColumnRead>> {
        const requestOptions = await this.updateProjectColumnProjectsProjectIdColumnsColumnIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectColumnReadFromJSON(jsonValue));
    }

    /**
     * Rename a workflow column for a project owned by the current user.
     * Update Project Column
     */
    async updateProjectColumnProjectsProjectIdColumnsColumnIdPatch(requestParameters: UpdateProjectColumnProjectsProjectIdColumnsColumnIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectColumnRead> {
        const response = await this.updateProjectColumnProjectsProjectIdColumnsColumnIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateProjectProjectsProjectIdPatch without sending the request
     */
    async updateProjectProjectsProjectIdPatchRequestOpts(requestParameters: UpdateProjectProjectsProjectIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling updateProjectProjectsProjectIdPatch().'
            );
        }

        if (requestParameters['projectUpdate'] == null) {
            throw new runtime.RequiredError(
                'projectUpdate',
                'Required parameter "projectUpdate" was null or undefined when calling updateProjectProjectsProjectIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/projects/{project_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectUpdateToJSON(requestParameters['projectUpdate']),
        };
    }

    /**
     * Update a project owned by the current user.
     * Update Project
     */
    async updateProjectProjectsProjectIdPatchRaw(requestParameters: UpdateProjectProjectsProjectIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectRead>> {
        const requestOptions = await this.updateProjectProjectsProjectIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectReadFromJSON(jsonValue));
    }

    /**
     * Update a project owned by the current user.
     * Update Project
     */
    async updateProjectProjectsProjectIdPatch(requestParameters: UpdateProjectProjectsProjectIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectRead> {
        const response = await this.updateProjectProjectsProjectIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateTaskEndpointProjectsProjectIdTasksTaskIdPatch without sending the request
     */
    async updateTaskEndpointProjectsProjectIdTasksTaskIdPatchRequestOpts(requestParameters: UpdateTaskEndpointProjectsProjectIdTasksTaskIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling updateTaskEndpointProjectsProjectIdTasksTaskIdPatch().'
            );
        }

        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling updateTaskEndpointProjectsProjectIdTasksTaskIdPatch().'
            );
        }

        if (requestParameters['taskUpdate'] == null) {
            throw new runtime.RequiredError(
                'taskUpdate',
                'Required parameter "taskUpdate" was null or undefined when calling updateTaskEndpointProjectsProjectIdTasksTaskIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/projects/{project_id}/tasks/{task_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"task_id"}}`, encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TaskUpdateToJSON(requestParameters['taskUpdate']),
        };
    }

    /**
     * Update a task in a project accessible to the current user.
     * Update Task Endpoint
     */
    async updateTaskEndpointProjectsProjectIdTasksTaskIdPatchRaw(requestParameters: UpdateTaskEndpointProjectsProjectIdTasksTaskIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskRead>> {
        const requestOptions = await this.updateTaskEndpointProjectsProjectIdTasksTaskIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskReadFromJSON(jsonValue));
    }

    /**
     * Update a task in a project accessible to the current user.
     * Update Task Endpoint
     */
    async updateTaskEndpointProjectsProjectIdTasksTaskIdPatch(requestParameters: UpdateTaskEndpointProjectsProjectIdTasksTaskIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskRead> {
        const response = await this.updateTaskEndpointProjectsProjectIdTasksTaskIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
