// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  TaskCreate,
  TaskDestination,
  TaskRead,
  TaskUpdate,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    TaskCreateFromJSON,
    TaskCreateToJSON,
    TaskDestinationFromJSON,
    TaskDestinationToJSON,
    TaskReadFromJSON,
    TaskReadToJSON,
    TaskUpdateFromJSON,
    TaskUpdateToJSON,
} from '../models/index';

export interface CreateTaskEndpointProjectsProjectIdTasksPostRequest {
    projectId: string;
    taskCreate: TaskCreate;
}

export interface DeleteTaskEndpointProjectsProjectIdTasksTaskIdDeleteRequest {
    projectId: string;
    taskId: string;
}

export interface GetTaskEndpointProjectsProjectIdTasksTaskIdGetRequest {
    projectId: string;
    taskId: string;
}

export interface ListActiveSprintTasksEndpointProjectsProjectIdTasksActiveSprintGetRequest {
    projectId: string;
}

export interface ListTasksEndpointProjectsProjectIdTasksGetRequest {
    projectId: string;
    title?: string | null;
    limit?: number | null;
    excludeTaskId?: string | null;
}

export interface MoveTaskEndpointProjectsProjectIdTasksTaskIdMovePutRequest {
    projectId: string;
    taskId: string;
    taskDestination: TaskDestination;
}

export interface UpdateTaskEndpointProjectsProjectIdTasksTaskIdPatchRequest {
    projectId: string;
    taskId: string;
    taskUpdate: TaskUpdate;
}

/**
 * 
 */
export class TasksApi extends runtime.BaseAPI {

    /**
     * Creates request options for createTaskEndpointProjectsProjectIdTasksPost without sending the request
     */
    async createTaskEndpointProjectsProjectIdTasksPostRequestOpts(requestParameters: CreateTaskEndpointProjectsProjectIdTasksPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling createTaskEndpointProjectsProjectIdTasksPost().'
            );
        }

        if (requestParameters['taskCreate'] == null) {
            throw new runtime.RequiredError(
                'taskCreate',
                'Required parameter "taskCreate" was null or undefined when calling createTaskEndpointProjectsProjectIdTasksPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/projects/{project_id}/tasks`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TaskCreateToJSON(requestParameters['taskCreate']),
        };
    }

    /**
     * Create a task in a project accessible to the current user.
     * Create Task Endpoint
     */
    async createTaskEndpointProjectsProjectIdTasksPostRaw(requestParameters: CreateTaskEndpointProjectsProjectIdTasksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskRead>> {
        const requestOptions = await this.createTaskEndpointProjectsProjectIdTasksPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskReadFromJSON(jsonValue));
    }

    /**
     * Create a task in a project accessible to the current user.
     * Create Task Endpoint
     */
    async createTaskEndpointProjectsProjectIdTasksPost(requestParameters: CreateTaskEndpointProjectsProjectIdTasksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskRead> {
        const response = await this.createTaskEndpointProjectsProjectIdTasksPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteTaskEndpointProjectsProjectIdTasksTaskIdDelete without sending the request
     */
    async deleteTaskEndpointProjectsProjectIdTasksTaskIdDeleteRequestOpts(requestParameters: DeleteTaskEndpointProjectsProjectIdTasksTaskIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling deleteTaskEndpointProjectsProjectIdTasksTaskIdDelete().'
            );
        }

        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling deleteTaskEndpointProjectsProjectIdTasksTaskIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects/{project_id}/tasks/{task_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"task_id"}}`, encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a task from a project accessible to the current user.
     * Delete Task Endpoint
     */
    async deleteTaskEndpointProjectsProjectIdTasksTaskIdDeleteRaw(requestParameters: DeleteTaskEndpointProjectsProjectIdTasksTaskIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteTaskEndpointProjectsProjectIdTasksTaskIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a task from a project accessible to the current user.
     * Delete Task Endpoint
     */
    async deleteTaskEndpointProjectsProjectIdTasksTaskIdDelete(requestParameters: DeleteTaskEndpointProjectsProjectIdTasksTaskIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTaskEndpointProjectsProjectIdTasksTaskIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getTaskEndpointProjectsProjectIdTasksTaskIdGet without sending the request
     */
    async getTaskEndpointProjectsProjectIdTasksTaskIdGetRequestOpts(requestParameters: GetTaskEndpointProjectsProjectIdTasksTaskIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getTaskEndpointProjectsProjectIdTasksTaskIdGet().'
            );
        }

        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling getTaskEndpointProjectsProjectIdTasksTaskIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects/{project_id}/tasks/{task_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"task_id"}}`, encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single task from a project accessible to the current user.
     * Get Task Endpoint
     */
    async getTaskEndpointProjectsProjectIdTasksTaskIdGetRaw(requestParameters: GetTaskEndpointProjectsProjectIdTasksTaskIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskRead>> {
        const requestOptions = await this.getTaskEndpointProjectsProjectIdTasksTaskIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskReadFromJSON(jsonValue));
    }

    /**
     * Get a single task from a project accessible to the current user.
     * Get Task Endpoint
     */
    async getTaskEndpointProjectsProjectIdTasksTaskIdGet(requestParameters: GetTaskEndpointProjectsProjectIdTasksTaskIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskRead> {
        const response = await this.getTaskEndpointProjectsProjectIdTasksTaskIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listActiveSprintTasksEndpointProjectsProjectIdTasksActiveSprintGet without sending the request
     */
    async listActiveSprintTasksEndpointProjectsProjectIdTasksActiveSprintGetRequestOpts(requestParameters: ListActiveSprintTasksEndpointProjectsProjectIdTasksActiveSprintGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling listActiveSprintTasksEndpointProjectsProjectIdTasksActiveSprintGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects/{project_id}/tasks/active-sprint`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List tasks selected into the project\'s active sprint.
     * List Active Sprint Tasks Endpoint
     */
    async listActiveSprintTasksEndpointProjectsProjectIdTasksActiveSprintGetRaw(requestParameters: ListActiveSprintTasksEndpointProjectsProjectIdTasksActiveSprintGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TaskRead>>> {
        const requestOptions = await this.listActiveSprintTasksEndpointProjectsProjectIdTasksActiveSprintGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TaskReadFromJSON));
    }

    /**
     * List tasks selected into the project\'s active sprint.
     * List Active Sprint Tasks Endpoint
     */
    async listActiveSprintTasksEndpointProjectsProjectIdTasksActiveSprintGet(requestParameters: ListActiveSprintTasksEndpointProjectsProjectIdTasksActiveSprintGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TaskRead>> {
        const response = await this.listActiveSprintTasksEndpointProjectsProjectIdTasksActiveSprintGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listTasksEndpointProjectsProjectIdTasksGet without sending the request
     */
    async listTasksEndpointProjectsProjectIdTasksGetRequestOpts(requestParameters: ListTasksEndpointProjectsProjectIdTasksGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling listTasksEndpointProjectsProjectIdTasksGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['title'] != null) {
            queryParameters['title'] = requestParameters['title'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['excludeTaskId'] != null) {
            queryParameters['exclude_task_id'] = requestParameters['excludeTaskId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/projects/{project_id}/tasks`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List tasks for a project accessible to the current user.
     * List Tasks Endpoint
     */
    async listTasksEndpointProjectsProjectIdTasksGetRaw(requestParameters: ListTasksEndpointProjectsProjectIdTasksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TaskRead>>> {
        const requestOptions = await this.listTasksEndpointProjectsProjectIdTasksGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TaskReadFromJSON));
    }

    /**
     * List tasks for a project accessible to the current user.
     * List Tasks Endpoint
     */
    async listTasksEndpointProjectsProjectIdTasksGet(requestParameters: ListTasksEndpointProjectsProjectIdTasksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TaskRead>> {
        const response = await this.listTasksEndpointProjectsProjectIdTasksGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for moveTaskEndpointProjectsProjectIdTasksTaskIdMovePut without sending the request
     */
    async moveTaskEndpointProjectsProjectIdTasksTaskIdMovePutRequestOpts(requestParameters: MoveTaskEndpointProjectsProjectIdTasksTaskIdMovePutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling moveTaskEndpointProjectsProjectIdTasksTaskIdMovePut().'
            );
        }

        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling moveTaskEndpointProjectsProjectIdTasksTaskIdMovePut().'
            );
        }

        if (requestParameters['taskDestination'] == null) {
            throw new runtime.RequiredError(
                'taskDestination',
                'Required parameter "taskDestination" was null or undefined when calling moveTaskEndpointProjectsProjectIdTasksTaskIdMovePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/projects/{project_id}/tasks/{task_id}/move`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"task_id"}}`, encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TaskDestinationToJSON(requestParameters['taskDestination']),
        };
    }

    /**
     * Move a task to a board destination accessible to the current user.
     * Move Task Endpoint
     */
    async moveTaskEndpointProjectsProjectIdTasksTaskIdMovePutRaw(requestParameters: MoveTaskEndpointProjectsProjectIdTasksTaskIdMovePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskRead>> {
        const requestOptions = await this.moveTaskEndpointProjectsProjectIdTasksTaskIdMovePutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskReadFromJSON(jsonValue));
    }

    /**
     * Move a task to a board destination accessible to the current user.
     * Move Task Endpoint
     */
    async moveTaskEndpointProjectsProjectIdTasksTaskIdMovePut(requestParameters: MoveTaskEndpointProjectsProjectIdTasksTaskIdMovePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskRead> {
        const response = await this.moveTaskEndpointProjectsProjectIdTasksTaskIdMovePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateTaskEndpointProjectsProjectIdTasksTaskIdPatch without sending the request
     */
    async updateTaskEndpointProjectsProjectIdTasksTaskIdPatchRequestOpts(requestParameters: UpdateTaskEndpointProjectsProjectIdTasksTaskIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling updateTaskEndpointProjectsProjectIdTasksTaskIdPatch().'
            );
        }

        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling updateTaskEndpointProjectsProjectIdTasksTaskIdPatch().'
            );
        }

        if (requestParameters['taskUpdate'] == null) {
            throw new runtime.RequiredError(
                'taskUpdate',
                'Required parameter "taskUpdate" was null or undefined when calling updateTaskEndpointProjectsProjectIdTasksTaskIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/projects/{project_id}/tasks/{task_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"task_id"}}`, encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TaskUpdateToJSON(requestParameters['taskUpdate']),
        };
    }

    /**
     * Update a task in a project accessible to the current user.
     * Update Task Endpoint
     */
    async updateTaskEndpointProjectsProjectIdTasksTaskIdPatchRaw(requestParameters: UpdateTaskEndpointProjectsProjectIdTasksTaskIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskRead>> {
        const requestOptions = await this.updateTaskEndpointProjectsProjectIdTasksTaskIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskReadFromJSON(jsonValue));
    }

    /**
     * Update a task in a project accessible to the current user.
     * Update Task Endpoint
     */
    async updateTaskEndpointProjectsProjectIdTasksTaskIdPatch(requestParameters: UpdateTaskEndpointProjectsProjectIdTasksTaskIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskRead> {
        const response = await this.updateTaskEndpointProjectsProjectIdTasksTaskIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
